import {
  agencies,
  executiveKPIs,
  funnelData,
  issues,
  milestones,
  monthlyIntakeData,
  opportunities,
  permits,
  projects,
  sectorInvestmentData,
  serviceRequests,
  services,
  users,
} from '../data/mockData';

export type Language = 'en' | 'vi';

const textMap: Record<string, string> = {
  'complete': 'Hoàn thành',
};

const cleanTextMap: Record<string, string> = {
  "complete": "Hoàn thành",
  "Description":"Mô tả",
  "incomplete": "Chưa hoàn thành",
  "Due date": "Hạn nộp",
  "Reminder timing": "Nhắc việc",
  "5 days before due date": "5 ngày trước hạn",
  "10 days before due date": "10 ngày trước hạn",
  "days before due date": "ngày trước hạn",
  "Required data owner alerts": "Cảnh báo dữ liệu được giao",
  "Overdue": "Quá hạn",
  "Due soon": "Sắp đến hạn",
  "Due in": "Đến hạn sau",
  "Overdue items": "Hạng mục quá hạn",
  "New Opportunity": "Cơ hội mới",
  "Nguyen Corp submitted an intake for Smart City project": "Nguyen Corp đã gửi hồ sơ quan tâm cho dự án đô thị thông minh",
  "Permit Approved": "Giấy phép đã được phê duyệt",
  "Construction permit for Da Nang Resort has been approved": "Giấy phép xây dựng cho khu du lịch ven sông TP. Hồ Chí Minh đã được phê duyệt",
  "SLA Warning": "Cảnh báo SLA",
  "Service request SR-2024-018 is approaching deadline": "Yêu cầu dịch vụ SR-2024-018 sắp đến hạn xử lý",
  "Milestone Completed": "Đã hoàn thành mốc tiến độ",
  "Phase 1 of Renewable Energy Park is complete": "Giai đoạn 1 của công viên năng lượng tái tạo đã hoàn thành",
  "Investor": "Nhà đầu tư",
  "Government Operator": "Cán bộ chính phủ",
  "Agency User": "Cán bộ cơ quan",
  "System Admin": "Quản trị hệ thống",
  "Executive / Leader": "Lãnh đạo điều hành",
  "Investor Portal": "Cổng nhà đầu tư",
  "Government Portal": "Cổng chính phủ",
  "Agency Portal": "Cổng cơ quan",
  "Admin Console": "Bảng điều khiển quản trị",
  "Executive View": "Góc nhìn điều hành",
  "Project Explorer": "Khám phá dự án",
  "My Watchlist": "Danh sách theo dõi",
  "My Opportunities": "Cơ hội của tôi",
  "Execution Workspace": "Không gian triển khai",
  "B2G Services": "Dịch vụ công",
  "Service Requests": "Yêu cầu dịch vụ",
  "Support": "Hỗ trợ",
  "Project Management": "Quản lý dự án",
  "Data Quality": "Chất lượng dữ liệu",
  "Opportunity Pipeline": "Phễu cơ hội",
  "Execution Monitor": "Giám sát triển khai",
  "Permit Tracker": "Theo dõi giấy phép",
  "Issue Management": "Quản lý vướng mắc",
  "Milestone Tracking": "Theo dõi tiến độ",
  "Service Workflow": "Quy trình dịch vụ",
  "User & Roles": "Người dùng và vai trò",
  "Agency Management": "Quản lý cơ quan",
  "Executive Dashboard": "Bảng điều hành",
  "Analytics": "Phân tích",
  "Risk Monitor": "Theo dõi rủi ro",
  "Vietnam Investment": "Đầu tư Việt Nam",
  "Vietnam Investment Agency": "Cơ quan Xúc tiến Đầu tư Việt Nam",
  "B2G Investment Platform": "Nền tảng Dịch vụ công",
  "Welcome to the Investment": "Chào mừng đến với Nền tảng",
  "Management Platform": "Quản lý Đầu tư",
  "Select your portal": "Chọn cổng truy cập",
  "Choose the role-based workspace that matches the way you work with Vietnam\\'s B2G investment pipeline.": "Chọn không gian làm việc theo vai trò phù hợp với cách bạn vận hành trong toàn bộ phễu đầu tư B2G của Việt Nam.",
  "Operational at a glance": "Toàn cảnh vận hành",
  "HCMC Investment Explorer": "Khám phá đầu tư TP.HCM",
  "Ho Chi Minh City Hot News": "Tin nóng TP. Hồ Chí Minh",
  "Investor pulse": "Nhịp đầu tư",
  "Hot News": "Tin nóng",
  "Green Growth": "Tăng trưởng xanh",
  "Send B2G Request": "Gửi yêu cầu B2G",
  "Report Issue": "Báo cáo vướng mắc",
  "Execution Actions": "Hành động triển khai",
  "Choose an action for the selected portfolio item.": "Chọn một hành động cho hạng mục danh mục đang được chọn.",
  "Open a structured investor question and route it to the project response queue.": "Tạo câu hỏi có cấu trúc của nhà đầu tư và chuyển vào hàng đợi phản hồi của dự án.",
  "Route a B2G workflow request for the selected project.": "Chuyển một yêu cầu quy trình B2G cho dự án đang được chọn.",
  "Log an execution blocker or coordination risk for the selected project.": "Ghi nhận một điểm nghẽn triển khai hoặc rủi ro điều phối cho dự án đang được chọn.",
  "Schedule a coordination request with the responsible public-sector team.": "Lên lịch một yêu cầu điều phối với đội ngũ khu vực công phụ trách.",
  "Question submitted": "Đã gửi câu hỏi",
  "B2G request submitted": "Đã gửi yêu cầu B2G",
  "Issue reported": "Đã báo cáo vướng mắc",
  "Meeting request submitted": "Đã gửi yêu cầu cuộc họp",
  "This question is now visible in the public Q&A stream and routed for response.": "Câu hỏi này hiện đã hiển thị trong luồng Hỏi đáp công khai và được chuyển để phản hồi.",
  "This request has been routed into the B2G workflow queue.": "Yêu cầu này đã được chuyển vào hàng đợi quy trình B2G.",
  "This issue is now tracked in the execution risk log.": "Vướng mắc này hiện đã được theo dõi trong nhật ký rủi ro triển khai.",
  "This meeting request has been routed for coordination.": "Yêu cầu cuộc họp này đã được chuyển để điều phối.",
  "Execution Coordination Request": "Yêu cầu điều phối triển khai",
  "Permit Acceleration Request": "Yêu cầu thúc đẩy thủ tục giấy phép",
  "Documentation Alignment Request": "Yêu cầu đồng bộ tài liệu",
  "Assigned agency": "Cơ quan phụ trách",
  "Submit request": "Gửi yêu cầu",
  "Issue summary": "Tóm tắt vướng mắc",
  "Issue detail": "Chi tiết vướng mắc",
  "Summarize the blocker or execution risk": "Tóm tắt điểm nghẽn hoặc rủi ro triển khai",
  "Describe the blocker, impact, and what needs to be resolved.": "Mô tả điểm nghẽn, tác động và nội dung cần được xử lý.",
  "Permitting": "Giấy phép",
  "Utilities": "Hạ tầng tiện ích",
  "Site access": "Tiếp cận hiện trường",
  "Legal": "Pháp lý",
  "Stakeholder coordination": "Điều phối các bên liên quan",
  "Priority": "Mức độ ưu tiên",
  "Thu Duc innovation corridor draws fresh interest from technology and advanced manufacturing investors": "Hành lang đổi mới sáng tạo Thủ Đức đang thu hút thêm sự quan tâm từ các nhà đầu tư công nghệ và sản xuất tiên tiến",
  "New planning momentum is reinforcing demand for mixed-use campuses, R&D facilities, and export-oriented production space.": "Động lực quy hoạch mới đang củng cố nhu cầu cho các khu phức hợp đa chức năng, cơ sở R&D và không gian sản xuất hướng xuất khẩu.",
  "Metro-linked development zones are strengthening the case for transit-oriented commercial and residential projects": "Các khu phát triển gắn với tuyến metro đang làm nổi bật tiềm năng của các dự án thương mại và nhà ở định hướng giao thông công cộng",
  "Improved connectivity is reshaping site attractiveness across gateway districts and key growth corridors.": "Kết nối hạ tầng được cải thiện đang tái định hình sức hấp dẫn của các địa điểm tại các quận cửa ngõ và các hành lang tăng trưởng trọng điểm.",
  "Clean energy and circular-economy projects continue to stand out in Ho Chi Minh City investment conversations": "Các dự án năng lượng sạch và kinh tế tuần hoàn tiếp tục nổi bật trong các cuộc trao đổi đầu tư tại TP. Hồ Chí Minh",
  "Investors are prioritizing platforms that combine industrial scale, sustainability targets, and public-sector alignment.": "Nhà đầu tư đang ưu tiên các nền tảng kết hợp quy mô công nghiệp, mục tiêu bền vững và sự đồng bộ với khu vực công.",
  "Discover investment-ready projects with verified public-sector data": "Khám phá các dự án sẵn sàng đầu tư với dữ liệu khu vực công đã được xác thực",
  "Evaluate projects through a structured public-investment lens: readiness, scale, location, incentives, and verified operating context.": "Đánh giá dự án theo góc nhìn đầu tư công có cấu trúc: mức độ sẵn sàng, quy mô, vị trí, ưu đãi và bối cảnh vận hành đã được xác thực.",
  "Showing": "Hiển thị",
  "projects": "dự án",
  "Watch": "Theo dõi",
  "Watching": "Đang theo dõi",
  "Follow": "Theo dõi",
  "View detail": "Xem chi tiết",
  "Social proof": "Mức độ quan tâm",
  "followers": "người theo dõi",
  "View project": "Xem dự án",
  "No projects found": "Không tìm thấy dự án",
  "Try adjusting your filters to explore other projects.": "Hãy điều chỉnh bộ lọc để xem thêm các dự án khác.",
  "Project not found": "Không tìm thấy dự án",
  "Return to explorer": "Quay lại trang khám phá",
  "Explorer": "Khám phá",
  "Verified": "Đã xác thực",
  "Investment scale with": "Quy mô đầu tư với",
  "Investment scale": "Quy mô đầu tư",
  "and structured incentives.": "và hệ thống ưu đãi có cấu trúc.",
  "Express Interest": "Bày tỏ quan tâm",
  "Request Meeting": "Yêu cầu cuộc họp",
  "Ask Question": "Đặt câu hỏi",
  "Investment Profile": "Hồ sơ đầu tư",
  "Minimum ticket": "Đầu tư tối thiểu",
  "Expected IRR": "IRR kỳ vọng",
  "Land area": "Diện tích đất",
  "CompletionMeter":"Mức độ đầy đủ dữ liệu",
  "New Draft Project":"Dự án mới",
  "Publish":"Công bố",
  "Data completeness": "Mức độ đầy đủ dữ liệu",
  "Data Completeness": "Mức độ đầy đủ dữ liệu",
  "Primary Details": "Thông tin chính",
  "Location & access": "Vị trí và kết nối",
  "Investment readiness": "Mức độ sẵn sàng đầu tư",
  "Project summary": "Tóm tắt dự án",
  "Secondary Details": "Thông tin bổ sung",
  "Project Documents": "Tài liệu dự án",
  "Uploaded": "Đã tải lên",
  "Download PDF": "Tải PDF",
  "Overview": "Tổng quan",
  "Name": "Tên dự án",
  "Minimum Investment": "Đầu tư tối thiểu",
  "Project Stage": "Giai đoạn dự án",
  "Required Data Ownership": "Phân công dữ liệu bắt buộc",
  "Required data": "Dữ liệu bắt buộc",
  "Attachment": "Tệp đính kèm",
  "Attachment file name": "Tên tệp đính kèm",
  "Last upload date": "Ngày tải lên gần nhất",
  "Owner note": "Ghi chú phụ trách",
  "Project Jobs": "Đầu việc dự án",
  "Project job": "Đầu việc dự án",
  "Job Title": "Tên đầu việc",
  "Job Description": "Mô tả đầu việc",
  "Project Processing": "Tiến độ xử lý dự án",
  "required jobs completed": "đầu việc bắt buộc đã hoàn thành",
  "required data items completed": "hạng mục dữ liệu bắt buộc đã hoàn thành",
  "data items": "hạng mục dữ liệu",
  "jobs": "đầu việc",
  "Single project record": "Hồ sơ dự án chuẩn hóa",
  "Standard project record": "Bản ghi dự án chuẩn hóa",
  "Investment-ready record": "Hồ sơ sẵn sàng cho nhà đầu tư",
  "Manage one standardized project record with overview data, required data ownership, and delivery jobs.": "Quản lý một hồ sơ dự án chuẩn hóa với phần tổng quan, dữ liệu bắt buộc và đầu việc triển khai.",
  "Define the required project data, assign the PIC, track due dates, and keep the latest supporting attachment visible.": "Xác định dữ liệu bắt buộc của dự án, giao PIC, theo dõi hạn xử lý và hiển thị tệp hỗ trợ mới nhất.",
  "Track the delivery process with accountable jobs, due dates, notes, and the latest uploaded work product.": "Theo dõi quá trình triển khai với đầu việc có người chịu trách nhiệm, hạn xử lý, ghi chú và tệp công việc mới nhất.",
  "Define at least one required data item and assign an owner.": "Xác định ít nhất một hạng mục dữ liệu bắt buộc và giao người phụ trách.",
  "Complete all required data items before final publication review.": "Hoàn thành tất cả hạng mục dữ liệu bắt buộc trước khi rà soát công bố cuối cùng.",
  "Define at least one project job to establish the delivery process.": "Xác định ít nhất một đầu việc dự án để thiết lập quy trình triển khai.",
  "Close outstanding project jobs to reach full processing readiness.": "Hoàn tất các đầu việc còn mở để đạt mức sẵn sàng xử lý đầy đủ.",
  "Update the overview data and save when you are ready to publish the new baseline.": "Cập nhật dữ liệu tổng quan và lưu khi bạn sẵn sàng công bố đường cơ sở mới.",
  "Project overview, required data, and processing jobs now stay aligned across government and investor views during this local session.": "Tổng quan dự án, dữ liệu bắt buộc và đầu việc xử lý giờ đã đồng bộ giữa màn hình chính phủ và nhà đầu tư trong phiên cục bộ này.",
  "No project jobs have been defined for this project yet.": "Chưa có đầu việc dự án nào được khai báo cho dự án này.",
  "Add project job": "Thêm đầu việc dự án",
  "Supporting Documents": "Tài liệu hỗ trợ",
  "Trust Signals": "Tín hiệu tin cậy",
  "Verified listing with structured investment data.": "Danh mục đã được xác thực với dữ liệu đầu tư có cấu trúc.",
  "investors are following this project.": "nhà đầu tư đang theo dõi dự án này.",
  "public questions are available for due diligence.": "câu hỏi công khai hiện có cho quá trình thẩm định.",
  "Public Q&A": "Hỏi đáp công khai",
  "Official answer": "Phản hồi chính thức",
  "Awaiting response from the data owner.": "Đang chờ phản hồi từ đơn vị quản lý dữ liệu.",
  "Ask a question": "Đặt câu hỏi",
  "Ask about legal status, incentives, planning controls, or delivery readiness...": "Hỏi về pháp lý, ưu đãi, quy hoạch hoặc mức độ sẵn sàng triển khai...",
  "Submit question": "Gửi câu hỏi",
  "Milestones": "Các mốc tiến độ",
  "Due": "Hạn",
  "Project list": "Danh sách dự án",
  "Edit project": "Chỉnh sửa dự án",
  "Budget": "Ngân sách",
  "Min Investment": "Đầu tư tối thiểu",
  "Followers": "Người theo dõi",
  "Execution Readiness": "Mức độ sẵn sàng triển khai",
  "Publish-ready": "Sẵn sàng công bố",
  "Needs attention": "Cần rà soát",
  "Project Highlights": "Điểm nổi bật của dự án",
  "signals": "tín hiệu",
  "Milestone Schedule": "Lịch mốc tiến độ",
  "milestones": "mốc",
  "No milestones have been defined yet.": "Chưa có mốc tiến độ nào được thiết lập.",
  "Documents": "Tài liệu",
  "No supporting documents uploaded yet.": "Chưa có tài liệu hỗ trợ nào được tải lên.",
  "Project Overview": "Tổng quan dự án",
  "Reference": "Tham chiếu",
  "Location": "Vị trí",
  "Land Area": "Diện tích đất",
  "Projected Jobs": "Việc làm dự kiến",
  "Published Date": "Ngày công bố",
  "Not published yet": "Chưa công bố",
  "Investor Q&A": "Hỏi đáp nhà đầu tư",
  "Asked by": "Hỏi bởi",
  "on": "vào ngày",
  "No investor questions have been submitted yet.": "Chưa có câu hỏi nào từ nhà đầu tư.",
  "Awaiting official response from the project team.": "Đang chờ phản hồi chính thức từ nhóm dự án.",
  "Home": "Trang chủ",
  "HCMInvHub": "HCMInvHub",
  "Lead-generation homepage": "Trang chủ thu hút nhu cầu đầu tư",
  "Explore Opportunities": "Khám phá cơ hội",
  "Opportunities": "Cơ hội đầu tư",
  "City briefing": "Thông tin thành phố",
  "Continue to": "Tiếp tục đến",
  "Investor portal": "cổng nhà đầu tư",
  "Government portal": "cổng chính phủ",
  "Agency portal": "cổng cơ quan",
  "Admin console": "bảng điều khiển quản trị",
  "Executive view": "góc nhìn điều hành",
  "Login / create account": "Đăng nhập / tạo tài khoản",
  "Request flow completed": "Luồng yêu cầu đã hoàn tất",
  "Your information has been saved, converted into a tracked request, and routed to the right team.": "Thông tin của bạn đã được lưu, chuyển thành yêu cầu theo dõi và chuyển tới đúng bộ phận phụ trách.",
  "Homepage entry point": "Điểm vào trang chủ",
  "Find Ho Chi Minh City investment opportunities with clearer signals and faster next steps.": "Tìm kiếm cơ hội đầu tư tại TP. Hồ Chí Minh với tín hiệu rõ ràng hơn và bước tiếp theo nhanh hơn.",
  "View the market, explore curated projects, understand the opportunity, and move into an active lead flow without losing momentum.": "Xem bức tranh thị trường, khám phá các dự án được tuyển chọn, hiểu rõ cơ hội và chuyển ngay sang luồng xử lý nhu cầu mà không mất đà.",
  "Published leads": "Dự án đang mở nhu cầu",
  "Project value": "Tổng giá trị dự án",
  "Investor markets": "Thị trường nhà đầu tư",
  "Large hero banner": "Hero banner lớn",
  "Current opportunity pulse": "Nhịp cơ hội hiện tại",
  "Move from market exploration to structured request creation in one page.": "Chuyển từ khám phá thị trường sang tạo yêu cầu có cấu trúc ngay trên một trang.",
  "Verified by current project data": "Được xác thực bằng dữ liệu dự án hiện có",
  "The homepage is driven by the same project records already used across the investor and government portals.": "Trang chủ sử dụng cùng bộ hồ sơ dự án đang được dùng trong cổng nhà đầu tư và cổng chính phủ.",
  "Fast track entry": "Lối vào nhanh",
  "Can't find a suitable project?": "Không tìm thấy dự án phù hợp?",
  "Tell us your needs. We will support you. One short submission lets the team create a request, route it after login, and trigger the right notification path.": "Hãy cho chúng tôi biết nhu cầu của bạn. Chúng tôi sẽ hỗ trợ. Một biểu mẫu ngắn sẽ giúp đội ngũ tạo yêu cầu, chuyển tiếp sau khi đăng nhập và kích hoạt đúng luồng thông báo.",
  "Click fast track": "Chọn lối vào nhanh",
  "Fill one form": "Điền một biểu mẫu",
  "Create request": "Tạo yêu cầu",
  "Trigger notification": "Kích hoạt thông báo",
  "Suggested match": "Gợi ý phù hợp",
  "Single form": "Biểu mẫu đơn",
  "Express investor intent": "Thể hiện nhu cầu đầu tư",
  "Hide form": "Ẩn biểu mẫu",
  "Open form": "Mở biểu mẫu",
  "Contact name": "Tên người liên hệ",
  "Preferred sector": "Lĩnh vực ưu tiên",
  "Country": "Quốc gia",
  "Location need": "Nhu cầu vị trí",
  "Country, city, district, industrial zone, or coordinates": "Quốc gia, thành phố, quận/huyện, khu công nghiệp hoặc tọa độ",
  "Country, city, district, industrial zone, geo coordinates": "Quốc gia, thành phố, quận/huyện, khu công nghiệp, tọa độ địa lý",
  "What are you looking for?": "Bạn đang tìm gì?",
  "Describe the opportunity you want, your decision criteria, and any timeline or structuring needs.": "Mô tả cơ hội bạn đang tìm, tiêu chí ra quyết định và mọi yêu cầu về thời gian hoặc cấu trúc đầu tư.",
  "Submitting now will create a tracked request and notify the matching desk.": "Gửi ngay sẽ tạo một yêu cầu được theo dõi và thông báo cho bộ phận phụ trách đối sánh.",
  "Submitting now will hand off to login / account creation before the request is created.": "Gửi ngay sẽ chuyển sang bước đăng nhập / tạo tài khoản trước khi yêu cầu được tạo.",
  "Submit fast-track request": "Gửi yêu cầu lối vào nhanh",
  "Open the form to collect one structured lead request, then route it through login into the current project workflow.": "Mở biểu mẫu để ghi nhận một nhu cầu có cấu trúc, sau đó chuyển qua đăng nhập vào quy trình dự án hiện tại.",
  "Search & filter": "Tìm kiếm và bộ lọc",
  "Search the investment map through the signals that matter first.": "Tìm kiếm bản đồ đầu tư theo những tín hiệu quan trọng nhất trước tiên.",
  "Filter across sectors, granular locations, investment size, project status, and investment structure using the same project records already present in the platform.": "Lọc theo lĩnh vực, vị trí chi tiết, quy mô đầu tư, trạng thái dự án và cấu trúc đầu tư bằng chính các hồ sơ dự án đang có trên nền tảng.",
  "projects visible": "dự án hiển thị",
  "All sectors": "Tất cả lĩnh vực",
  "All wards": "Tất cả phường/xã",
  "All sizes": "Tất cả quy mô",
  "All statuses": "Tất cả trạng thái",
  "All types": "Tất cả loại hình",
  "An Khanh": "An Khánh",
  "An Loi Dong": "An Lợi Đông",
  "Ben Nghe": "Bến Nghé",
  "Ben Thanh": "Bến Thành",
  "Can Thanh": "Cần Thạnh",
  "Cat Lai": "Cát Lái",
  "Da Kao": "Đa Kao",
  "Hiep Phu": "Hiệp Phú",
  "Linh Trung": "Linh Trung",
  "Long Binh": "Long Bình",
  "Long Phuoc": "Long Phước",
  "Ly Nhon": "Lý Nhơn",
  "Nhuan Duc": "Nhuận Đức",
  "Phu Huu": "Phú Hữu",
  "Tan My": "Tân Mỹ",
  "Tan Thong Hoi": "Tân Thông Hội",
  "Tang Nhon Phu": "Tăng Nhơn Phú",
  "Thanh An": "Thạnh An",
  "Thai My": "Thái Mỹ",
  "Thao Dien": "Thảo Điền",
  "Thu Thiem": "Thủ Thiêm",
  "Vo Thi Sau": "Võ Thị Sáu",
  "Xuan Hoa": "Xuân Hòa",
  "< $10M": "< 10 triệu USD",
  "$10M - $50M": "10 triệu - 50 triệu USD",
  "$50M - $200M": "50 triệu - 200 triệu USD",
  ">$200M": "> 200 triệu USD",
  "Attracting Interest": "Đang thu hút quan tâm",
  "In Process": "Đang xử lý",
  "Completed": "Hoàn tất",
  "Greenfield": "Dự án đầu tư mới",
  "Brownfield": "Dự án cải tạo/mở rộng",
  "Joint Venture": "Liên doanh",
  "PPP": "PPP",
  "Acquisition": "Mua lại",
  "High-Tech & Digital": "Công nghệ cao và số hóa",
  "Manufacturing & Industrial": "Sản xuất và công nghiệp",
  "Infrastructure & Logistics": "Hạ tầng và logistics",
  "Energy & Utilities": "Năng lượng và tiện ích",
  "Real Estate & Urban Development": "Bất động sản và phát triển đô thị",
  "Financial Services": "Dịch vụ tài chính",
  "Healthcare & Pharma": "Y tế và dược phẩm",
  "Education & Training": "Giáo dục và đào tạo",
  "Tourism & Hospitality": "Du lịch và lưu trú",
  "Retail & Consumer": "Bán lẻ và tiêu dùng",
  "Environmental & Waste Management": "Môi trường và quản lý chất thải",
  "Renewable Energy": "Năng lượng tái tạo",
  "Smart City & Urban Tech": "Đô thị thông minh và công nghệ đô thị",
  "Agriculture & Agritech": "Nông nghiệp và công nghệ nông nghiệp",
  "Food Processing & Supply Chain": "Chế biến thực phẩm và chuỗi cung ứng",
  "Social Infrastructure": "Hạ tầng xã hội",
  "R&D & Innovation": "R&D và đổi mới sáng tạo",
  "Supporting Industries": "Công nghiệp hỗ trợ",
  "Project name": "Tên dự án",
  "Sector": "Lĩnh vực",
  "Investment size": "Quy mô đầu tư",
  "Project status": "Trạng thái dự án",
  "Status": "Trạng thái",
  "Location mapping": "Bản đồ vị trí",
  "Key highlights": "Điểm nhấn chính",
  "City information": "Thông tin thành phố",
  "Give investors a city context before they decide whether to lean in.": "Cung cấp bối cảnh thành phố cho nhà đầu tư trước khi họ quyết định theo đuổi cơ hội.",
  "Economy": "Kinh tế",
  "Investment": "Đầu tư",
  "Culture": "Văn hóa",
  "Living environment": "Môi trường sống",
  "Read article": "Đọc bài viết",
  "HCMC eyes 10% GDP growth in H2": "TP.HCM hướng tới tăng trưởng GDP 10% trong nửa cuối năm",
  "A city-level growth push centered on exports, tourism, digitalization, and social investment.": "Một nỗ lực tăng trưởng cấp thành phố tập trung vào xuất khẩu, du lịch, số hóa và đầu tư xã hội.",
  "PM urges HCMC for policy changes to attract $200B investment by 2030": "Thủ tướng thúc đẩy TP.HCM điều chỉnh chính sách để thu hút 200 tỷ USD đầu tư đến năm 2030",
  "A policy and capital-mobilization lens on how Ho Chi Minh City is framing long-term investment demand.": "Góc nhìn về chính sách và huy động vốn cho thấy cách TP.HCM đang định hình nhu cầu đầu tư dài hạn.",
  "HCMC hosts first river festival": "TP.HCM tổ chức lễ hội sông nước đầu tiên",
  "A strong signal of place-branding, tourism activation, and cultural programming tied to the city waterfront.": "Một tín hiệu rõ nét về xây dựng thương hiệu điểm đến, kích hoạt du lịch và các chương trình văn hóa gắn với mặt nước đô thị.",
  "Ho Chi Minh City aims to join global top 100 liveable cities": "TP.HCM đặt mục tiêu vào top 100 thành phố đáng sống nhất thế giới",
  "A forward-looking read on livability goals, healthcare, education, safety, and modern urban life.": "Một góc nhìn hướng tới tương lai về mục tiêu đáng sống, y tế, giáo dục, an toàn và đời sống đô thị hiện đại.",
  "Contact Arobid for Support": "Liên hệ Arobid để được hỗ trợ",
  "Need guided support before you proceed?": "Bạn cần hỗ trợ định hướng trước khi tiếp tục?",
  "Use this form when you need help on project clarification, market entry, or government coordination. Login is required before the support request is created.": "Sử dụng biểu mẫu này khi bạn cần hỗ trợ làm rõ dự án, gia nhập thị trường hoặc điều phối với cơ quan nhà nước. Cần đăng nhập trước khi yêu cầu hỗ trợ được tạo.",
  "Project clarification": "Làm rõ thông tin dự án",
  "Market entry and incentives": "Gia nhập thị trường và ưu đãi đầu tư",
  "Meeting coordination": "Điều phối cuộc họp",
  "Government workflow support": "Hỗ trợ quy trình với cơ quan nhà nước",
  "Project": "Dự án",
  "Support topic": "Chủ đề hỗ trợ",
  "How can Arobid help?": "Arobid có thể hỗ trợ gì?",
  "Describe the support you need, the blockers you are facing, and what response would unblock the next step.": "Mô tả nội dung hỗ trợ bạn cần, các vướng mắc đang gặp và phản hồi nào sẽ giúp mở bước tiếp theo.",
  "Mark this as urgent": "Đánh dấu là khẩn",
  "This will create a support issue immediately.": "Việc này sẽ tạo ngay một yêu cầu hỗ trợ được theo dõi.",
  "Login is required before the support request is created.": "Cần đăng nhập trước khi yêu cầu hỗ trợ được tạo.",
  "Submit support request": "Gửi yêu cầu hỗ trợ",
  "Fast-track lead captured": "Đã ghi nhận nhu cầu lối vào nhanh",
  "Fast-track request routed to the investor matching queue.": "Yêu cầu lối vào nhanh đã được chuyển vào hàng đợi đối sánh nhà đầu tư.",
  "Request created. The team has been notified and the lead is now in the matching queue.": "Yêu cầu đã được tạo. Đội ngũ đã được thông báo và nhu cầu hiện đang nằm trong hàng đợi đối sánh.",
  "Complete company, contact, and email before continuing.": "Hãy hoàn thành thông tin doanh nghiệp, người liên hệ và email trước khi tiếp tục.",
  "Complete company, contact, email, and support message before submitting.": "Hãy hoàn thành thông tin doanh nghiệp, người liên hệ, email và nội dung hỗ trợ trước khi gửi.",
  "Support request submitted": "Đã gửi yêu cầu hỗ trợ",
  "Arobid support request routed to the responsible desk.": "Yêu cầu hỗ trợ Arobid đã được chuyển tới bộ phận phụ trách.",
  "Support request logged. The appropriate desk has been notified for follow-up.": "Yêu cầu hỗ trợ đã được ghi nhận. Bộ phận phù hợp đã được thông báo để theo dõi xử lý.",
  "Notifications": "Thông báo",
  "unread": "chưa đọc",
  "Switch Role": "Đổi vai trò",
  "Switch Role / Logout": "Đổi vai trò / Đăng xuất",
  "Welcome to the Investment Management Platform": "Chào mừng đến với Nền tảng Quản lý Đầu tư",
  "Platform v2.4 — 2024": "Nền tảng v2.4 - 2024",
  "Explore & Invest": "Khám phá và đầu tư",
  "Manage & Govern": "Quản lý và điều hành",
  "Process & Execute": "Xử lý và triển khai",
  "Configure & Control": "Cấu hình và kiểm soát",
  "Analyze & Decide": "Phân tích và ra quyết định",
  "Discover investment opportunities, submit intake forms, and manage your portfolio.": "Khám phá cơ hội đầu tư, gửi hồ sơ quan tâm và quản lý danh mục của bạn.",
  "Create and publish projects, manage investment pipeline, and oversee execution.": "Tạo và công bố dự án, quản lý phễu đầu tư và giám sát triển khai.",
  "Handle permits, resolve issues, track milestones, and process service requests.": "Xử lý giấy phép, giải quyết vướng mắc, theo dõi tiến độ và xử lý yêu cầu dịch vụ.",
  "Manage user roles, permissions, and agency configurations for the platform.": "Quản lý vai trò người dùng, phân quyền và cấu hình cơ quan trên nền tảng.",
  "View high-level KPIs, investment funnel analytics, and risk monitoring dashboards.": "Theo dõi KPI cấp cao, phân tích phễu đầu tư và bảng giám sát rủi ro.",
  "Select your role to access the appropriate portal for managing Vietnam\\'s B2G investment pipeline.": "Chọn vai trò để truy cập cổng phù hợp trong quá trình quản lý phễu đầu tư B2G của Việt Nam.",
  "Enter Portal": "Vào cổng",
  "Active Projects": "Dự án đang hoạt động",
  "Investment Pipeline": "Phễu đầu tư",
  "Approved Deals": "Thương vụ đã duyệt",
  "In Execution": "Đang triển khai",
  "Ministry of Planning & Investment, Vietnam. All rights reserved.": "Bộ Kế hoạch và Đầu tư Việt Nam. Bảo lưu mọi quyền.",
  "Open for Investment": "Mở gọi đầu tư",
  "Under Review": "Đang thẩm định",
  "Draft": "Bản nháp",
  "Pending": "Chờ xử lý",
  "In Review": "Đang xem xét",
  "Approved": "Đã phê duyệt",
  "Rejected": "Bị từ chối",
  "Info Required": "Cần bổ sung",
  "high": "cao",
  "medium": "trung bình",
  "low": "thấp",
  "critical": "nghiêm trọng",
  "active": "đang hoạt động",
  "inactive": "ngừng hoạt động",
  "National": "Cấp quốc gia",
  "Provincial": "Cấp tỉnh",
  "Institutional": "Tổ chức",
  "VC/PE": "Quỹ VC/PE",
  "Infrastructure Fund": "Quỹ hạ tầng",
  "Strategic": "Nhà đầu tư chiến lược",
  "South Korea": "Hàn Quốc",
  "Singapore": "Singapore",
  "Norway": "Na Uy",
  "Japan": "Nhật Bản",
  "USA": "Hoa Kỳ",
  "Infrastructure": "Hạ tầng",
  "Energy": "Năng lượng",
  "Manufacturing": "Sản xuất",
  "Tourism": "Du lịch",
  "Technology": "Công nghệ",
  "Agriculture": "Nông nghiệp",
  "Ho Chi Minh City": "TP. Ho Chi Minh",
  "Hanoi": "Hà Nội",
  "Da Nang": "Đà Nẵng",
  "Binh Thuan": "Bình Thuận",
  "Dong Nai": "Đồng Nai",
  "Can Tho": "Cần Thơ",
  "Ho Chi Minh City Smart Infrastructure Hub": "Trung tâm hạ tầng thông minh TP. Hồ Chí Minh",
  "Binh Thuan Renewable Energy Park": "Công viên năng lượng tái tạo Bình Thuận",
  "Dong Nai Industrial Zone Expansion": "Mở rộng khu công nghiệp Đồng Nai",
  "Da Nang Tourism & Resort Complex": "Tổ hợp du lịch và nghỉ dưỡng Đà Nẵng",
  "Hanoi Technology Innovation Hub": "Trung tâm đổi mới công nghệ Hà Nội",
  "Can Tho Agri-Processing Complex": "Tổ hợp chế biến nông sản Cần Thơ",
  "A landmark smart city development transforming Thu Duc into a world-class urban innovation center with integrated digital infrastructure, smart mobility solutions, and sustainable urban management systems.": "Dự án đô thị thông minh trọng điểm, chuyển đổi Thủ Đức thành trung tâm đổi mới đô thị đẳng cấp quốc tế với hạ tầng số tích hợp, giao thông thông minh và hệ thống quản trị đô thị bền vững.",
  "Integrated solar and wind energy park leveraging Binh Thuan\\'s exceptional natural resources to deliver clean energy to the national grid with guaranteed off-take agreements.": "Tổ hợp điện mặt trời và điện gió tận dụng lợi thế tự nhiên của Bình Thuận để cung cấp năng lượng sạch cho lưới điện quốc gia với cam kết bao tiêu đầu ra.",
  "Strategic industrial zone expansion adjacent to Long Thanh International Airport, designed for high-tech manufacturing, logistics, and export-oriented industries with full infrastructure support.": "Dự án mở rộng khu công nghiệp chiến lược liền kề sân bay quốc tế Long Thành, định hướng cho sản xuất công nghệ cao, logistics và công nghiệp xuất khẩu với hạ tầng đồng bộ.",
  "Premium integrated tourism development on Da Nang\\'s most coveted beachfront, combining 5-star hospitality, convention facilities, and entertainment within a UNESCO cultural heritage corridor.": "Dự án du lịch tích hợp cao cấp tại bãi biển đẹp nhất Đà Nẵng, kết hợp khách sạn 5 sao, trung tâm hội nghị và giải trí trong hành lang di sản văn hóa UNESCO.",
  "Vietnam\\'s flagship technology innovation cluster at Hoa Lac Hi-Tech Park, designed to attract R&D centers, semiconductor manufacturing, and deep-tech startups with world-class facilities.": "Cụm đổi mới công nghệ trọng điểm tại Khu công nghệ cao Hòa Lạc, thu hút trung tâm R&D, sản xuất bán dẫn và startup deep-tech với hạ tầng đẳng cấp quốc tế.",
  "Integrated agricultural processing and cold chain logistics complex in the heart of the Mekong Delta, serving Vietnam\\'s largest rice, seafood, and tropical fruit export region.": "Tổ hợp chế biến nông nghiệp và logistics chuỗi lạnh tại trung tâm Đồng bằng sông Cửu Long, phục vụ vùng xuất khẩu gạo, thủy sản và trái cây nhiệt đới lớn nhất Việt Nam.",
  "PPP Structure Available": "Có mô hình PPP",
  "Tax Incentives 15 Years": "Ưu đãi thuế 15 năm",
  "35-year Land Lease": "Thuê đất 35 năm",
  "Fast-track Licensing": "Cấp phép nhanh",
  "FIT Price Guaranteed": "Bảo đảm giá FIT",
  "20-year PPA Available": "Có PPA 20 năm",
  "Grid Connection Ready": "Sẵn sàng đấu nối lưới điện",
  "EPC Partners Available": "Có sẵn đi tác EPC",
  "Airport Adjacency": "Liền kề sân bay",
  "Corporate Tax Holiday 4Y": "Miễn thuế TNDN 4 năm",
  "One-Stop Service Center": "Trung tâm một cửa",
  "Skilled Labor Pool": "Nguồn lao động tay nghề cao",
  "Prime Beachfront Land": "Quỹ đất ven biển đắc địa",
  "Tourism Incentives 10Y": "Ưu đãi du lịch 10 năm",
  "Proven Tourism Market": "Thị trường du lịch đã kiểm chứng",
  "Heritage Site Access": "Kết nối khu di sản",
  "Hi-Tech Zone Benefits": "Ưu đãi khu công nghệ cao",
  "University Cluster Access": "Kết nối cụm đại học",
  "Talent Pipeline": "Nguồn nhân lực chất lượng",
  "R&D Tax Credits": "Ưu đãi thuế R&D",
  "Delta Location": "Vị trí trung tâm vùng đồng bằng",
  "Agri Export Hub": "Trung tâm xuất khẩu nông sản",
  "Cold Chain Infrastructure": "Hạ tầng chuỗi lạnh",
  "EVFTA Benefits": "Lợi thế EVFTA",
  "Investment Prospectus.pdf": "Hồ sơ mời đầu tư.pdf",
  "Environmental Impact Assessment.pdf": "Báo cáo đánh giá tác động môi trường.pdf",
  "Land Use Plan.pdf": "Quy hoạch sử dụng đất.pdf",
  "Energy Yield Assessment.pdf": "Đánh giá sản lượng năng lượng.pdf",
  "Grid Connection Study.pdf": "Nghiên cứu đấu nối lưới điện.pdf",
  "Industrial Zone Master Plan.pdf": "Quy hoạch tổng thể khu công nghiệp.pdf",
  "Infrastructure Specification.pdf": "Thông số hạ tầng kỹ thuật.pdf",
  "Tourism Feasibility Study.pdf": "Nghiên cứu khả thi du lịch.pdf",
  "Innovation Hub Concept.pdf": "Đề án trung tâm đổi mới sáng tạo.pdf",
  "What is the minimum equity contribution required for the PPP model?": "Tỷ lệ vốn chủ sở hữu tối thiểu cho mô hình PPP là bao nhiêu?",
  "Minimum equity contribution is 30% of total project value for the PPP structure.": "Tỷ lệ vốn chủ sở hữu tối thiểu là 30% tổng giá trị dự án đối với cấu trúc PPP.",
  "Are there restrictions on profit repatriation?": "Có hạn chế nào đối với việc chuyển lợi nhuận ra nước ngoài không?",
  "What is the current FIT tariff rate?": "Mức giá FIT hiện tại là bao nhiêu?",
  "Current solar FIT is 7.09 UScents/kWh and wind is 8.5 UScents/kWh.": "Giá FIT điện mặt trời hiện là 7,09 UScents/kWh và điện gió là 8,5 UScents/kWh.",
  "What is the maximum building height restriction near the heritage site?": "Giới hạn chiều cao công trình tối đa gần khu di sản là bao nhiêu?",
  "Phase 1": "Giai đoạn 1",
  "Phase 2": "Giai đoạn 2",
  "Phase 3": "Giai đoạn 3",
  "Site Preparation & Foundation": "Chuẩn bị mặt bằng và thi công móng",
  "Core Infrastructure Build": "Thi công hạ tầng cốt lõi",
  "Smart Systems Integration": "Tích hợp hệ thống thông minh",
  "Land Clearance & Site Setup": "Giải phóng mặt bằng và chuẩn bị công trường",
  "Equipment Procurement & Installation": "Mua sắm và lắp đặt thiết bị",
  "Grid Connection & Commissioning": "Đấu nối lưới điện và vận hành thử",
  "Infrastructure Development Zone A": "Phát triển hạ tầng khu A",
  "Zone B & C Development": "Phát triển khu B và C",
  "Hotel & Resort Core": "Khối khách sạn và khu nghệ dưỡng",
  "Convention & Entertainment": "Khu hội nghị và giải trí",
  "R&D Campus Construction": "Xây dựng khuôn viên R&D",
  "Intake form submitted": "Đã gửi hồ sơ quan tâm",
  "Due diligence package sent to investor": "Đã gửi bộ hồ sơ thẩm định cho nhà đầu tư",
  "Site visit completed with investor team": "Đã hoàn tất chuyến khảo sát hiện trường với nhà đầu tư",
  "Term sheet draft shared": "Đã chia sẻ dự thảo điều khoản đầu tư",
  "Technical assessment initiated": "Đã khởi động đánh giá kỹ thuật",
  "Under initial screening": "Đang sàng lọc ban đầu",
  "Qualified": "Đạt yêu cầu",
  "Due diligence completed": "Đã hoàn tất thẩm định",
  "Term sheet agreed": "Đã thống nhất điều khoản đầu tư",
  "Opportunity approved by Director": "Cơ hội đã được lãnh đạo phê duyệt",
  "Construction Permit": "Giấy phép xây dựng",
  "Environmental Permit": "Giấy phép môi trường",
  "Investment Registration": "Đăng ký đầu tư",
  "Land Use Rights Certificate": "Giấy chứng nhận quyền sử dụng đất",
  "Fire Safety Certificate": "Chứng nhận phòng cháy chữa cháy",
  "Grid Connection Permit": "Giấy phép đấu nối lưới điện",
  "Reviewing structural plans.": "Đang rà soát hồ sơ kết cấu.",
  "Approved with conditions.": "Đã phê duyệt kèm điều kiện.",
  "IRC issued successfully.": "Đã cấp IRC thành công.",
  "Missing fire suppression system drawings.": "Thiếu bản vẽ hệ thống chữa cháy.",
  "Technical review with EVN underway.": "Đang phối hợp EVN rà soát kỹ thuật.",
  "Site Boundary Dispute with Adjacent Landowner": "Tranh chấp ranh giới với chủ đất liền kề",
  "Landowner claims 2ha overlap with project boundary in Zone B. Legal review initiated.": "Chủ đất cho rằng có chồng lấn 2ha với ranh giới dự án tại khu B. Đã khởi động rà soát pháp lý.",
  "Grid Capacity Constraint - Delayed EVN Upgrade": "Hạn chế công suất lưới điện - EVN nâng cấp chậm tiến độ",
  "EVN transmission upgrade delayed by 3 months, affecting Phase 2 commissioning schedule.": "Việc nâng cấp truyền tải của EVN chậm 3 tháng, ảnh hưởng lịch vận hành giai đoạn 2.",
  "Environmental Compliance: Water Treatment Specification": "Tuân thủ môi trường: thông số xử lý nước thải",
  "Investor requested wastewater treatment capacity increase. Engineering review needed.": "Nhà đầu tư đề nghị nâng công suất xử lý nước thải. Cần rà soát kỹ thuật.",
  "Traffic Impact Assessment - Revised Routing": "Đánh giá tác động giao thông - điều chỉnh phương án luồng tuyến",
  "City transport authority requested revised traffic study for Zone A access roads.": "Cơ quan giao thông thành phố yêu cầu điều chỉnh nghiên cứu giao thông cho đường tiếp cận khu A.",
  "Heritage Zone Height Restriction Clarification": "Làm rõ giới hạn chiều cao tại khu di sản",
  "Conflicting regulations between local plan and national heritage protection act. Seeking MoC ruling.": "Có xung đột giữa quy hoạch địa phương và quy định bảo tồn di sản quốc gia. Đang xin ý kiến Bộ Xây dựng.",
  "Land": "Đất đai",
  "Environment": "Môi trường",
  "Transport": "Giao thông",
  "Regulatory": "Pháp lý",
  "Investment Registration Certificate": "Giấy chứng nhận đăng ký đầu tư",
  "Official IRC issued by the Department of Planning and Investment for foreign-invested enterprises.": "IRC do Sở Kế hoạch và Đầu tư cấp cho doanh nghiệp có vốn đầu tư nước ngoài.",
  "Enterprise Registration Certificate": "Giấy chứng nhận đểng ký doanh nghiệp",
  "ERC for establishing a legal entity in Vietnam.": "ERC để thành lập pháp nhân tại Việt Nam.",
  "Environmental Impact Assessment Approval": "Phê duyệt đánh giá tác động môi trường",
  "EIA approval from the Ministry of Natural Resources and Environment for industrial/energy projects.": "Phê duyệt EIA của Bộ Tài nguyên và Môi trường cho các dự án công nghiệp hoặc năng lượng.",
  "Building permit for construction of industrial, commercial or residential structures.": "Giấy phép xây dựng cho công trình công nghiệp, thương mại hoặc nhà ở.",
  "\"Red Book\" certification confirming land use rights allocation for the project site.": "Giấy chứng nhận quyền sử dụng đất xác nhận việc giao đất cho dự án.",
  "Import/Export License for Equipment": "Giấy phép xuất nhập khẩu thiết bị",
  "License for importing capital equipment exempt from import duties.": "Giấy phép nhập khẩu thiết bị vốn được miễn thuế nhập khẩu.",
  "Fire Prevention & Fighting Certificate": "Giấy chứng nhận phòng cháy chữa cháy",
  "Fire safety design approval and operational certificate for buildings.": "Thẩm duyệt thiết kế PCCC và cấp giấy chứng nhận vận hành cho công trình.",
  "Work Permit for Foreign Employees": "Giấy phép lao động cho lao động nước ngoài",
  "Work permits for foreign nationals employed in Vietnam-based projects.": "Giấy phép lao động cho người nước ngoài làm việc tại các dự án ở Việt Nam.",
  "15 working days": "15 ngày làm việc",
  "3 working days": "3 ngày làm việc",
  "30 working days": "30 ngày làm việc",
  "20 working days": "20 ngày làm việc",
  "5 working days": "5 ngày làm việc",
  "10 working days": "10 ngày làm việc",
  "7 working days": "7 ngày làm việc",
  "No fee": "Miễn phí",
  "Based on project scale": "Theo quy mô dự án",
  "Land-use fee based on area": "Tiền sử dụng đất theo diện tích",
  "Application form": "Mẫu đơn đề nghị",
  "Investment project proposal": "Đề xuất dự án đầu tư",
  "Investor charter docs": "Hồ sơ pháp lý của nhà đầu tư",
  "Financial capacity proof": "Chứng minh năng lực tài chính",
  "Charter": "Điều lệ",
  "Owner ID/Passport": "CMND/Hộ chiếu của chủ sở hữu",
  "Legal address proof": "Chứng từ địa chỉ hợp pháp",
  "EIA Report": "Báo cáo EIA",
  "Project technical documentation": "Tài liệu kỹ thuật dự án",
  "Site map & boundary": "Bản đồ và ranh giới khu đất",
  "Stakeholder consultation records": "Biên bản tham vấn các bên liên quan",
  "Construction design drawings": "Bản vẽ thiết kế xây dựng",
  "Land use rights docs": "Hồ sơ quyền sử dụng đất",
  "Fire safety pre-assessment": "Hồ sơ thẩm duyệt PCCC",
  "Structural calculation": "Tính toán kết cấu",
  "LURC application": "Đơn đề nghị cấp LURC",
  "Approved site plan": "Quy hoạch mặt bằng được duyệt",
  "Land survey report": "Báo cáo khảo sát đất",
  "Tax clearance certificate": "Giấy xác nhận hoàn thành nghĩa vụ thuế",
  "IRC copy": "Bản sao IRC",
  "Equipment list & specs": "Danh mục và thông số thiết bị",
  "Customs declaration form": "Tờ khai hải quan",
  "Supplier invoice": "Hóa đơn nhà cung cấp",
  "Fire safety design docs": "Hồ sơ thiết kế PCCC",
  "Construction permit copy": "Bản sao giấy phép xây dựng",
  "Equipment list": "Danh mục thiết bị",
  "Fire drill plan": "Kế hoạch diễn tập chữa cháy",
  "Criminal record": "Lý lịch tư pháp",
  "Health certificate": "Giấy khám sức khỏe",
  "Diplomas & CVs": "Bằng cấp và CV",
  "Passport copy": "Bản sao hộ chiếu",
  "submitted": "đã nộp",
  "processing": "đang xử lý",
  "approved": "đã phê duyệt",
  "rejected": "bị từ chối",
  "on_track": "đúng tiến độ",
  "at_risk": "có rủi ro",
  "breached": "quá hạn",
  "Executive": "Lãnh đạo",
  "Admin": "Quản trị viên",
  "Ministry of Planning & Investment": "Bộ Kế hoạch và Đầu tư",
  "Department of Planning and Investment":"Sở Kế hoạch và Đầu Tư Tp Hồ Chí Minh",
  "Korea Infrastructure Partners": "Korea Infrastructure Partners",
  "Dept. Planning & Investment, Da Nang": "Sở Kế hoạch và Đầu tư Đà Nẵng",
  "Department of Planning and Investment, Ho Chi Minh City": "Sở Kế hoạch và Đầu tư TP. Hồ Chí Minh",
  "Department of Natural Resources and Environment, Ho Chi Minh City": "Sở Tài nguyên và Môi trường TP. Hồ Chí Minh",
  "Department of Construction, Ho Chi Minh City": "Sở Xây dựng TP. Hồ Chí Minh",
  "Department of Labor, Invalids and Social Affairs, Ho Chi Minh City": "Sở Lao động - Thương binh và Xã hội TP. Hồ Chí Minh",
  "Fire Prevention and Fighting Police, Ho Chi Minh City": "Cảnh sát Phòng cháy Chữa cháy TP. Hồ Chí Minh",
  "Ho Chi Minh City Renewable Energy Integration Park": "Khu năng lượng tái tạo tích hợp TP. Hồ Chí Minh",
  "Ho Chi Minh City Advanced Manufacturing Zone": "Khu sản xuất công nghệ cao TP. Hồ Chí Minh",
  "Ho Chi Minh City Riverside Tourism & Convention Complex": "Tổ hợp du lịch và hội nghị ven sông TP. Hồ Chí Minh",
  "Ho Chi Minh City Technology Innovation Hub": "Trung tâm đổi mới công nghệ TP. Hồ Chí Minh",
  "Ho Chi Minh City Agri-Logistics & Processing Complex": "Tổ hợp logistics và chế biến nông sản TP. Hồ Chí Minh",
  "HCMC Renewable Integration Park": "Khu năng lượng tích hợp TP.HCM",
  "HCMC Advanced Manufacturing Zone": "Khu sản xuất công nghệ cao TP.HCM",
  "HCMC Riverside Tourism Complex": "Khu du lịch ven sông TP.HCM",
  "HCMC RE Integration Park": "Khu năng lượng tích hợp TP.HCM",
  "HCMC Manufacturing Zone": "Khu sản xuất TP.HCM",
  "HCMC Riverside Tourism": "Du lịch ven sông TP.HCM",
  "Project": "Dự án",
  "Just now": "Vừa xong",
  "Project Draft Created": "Đã tạo bản nháp dự án",
  "Project Published": "Dự án đã được công bố",
  "Service Request Submitted": "Đã gửi yêu cầu dịch vụ",
  "Service Workflow Updated": "Quy trình dịch vụ đã được cập nhật",
  "Support / Issue Logged": "Đã ghi nhận hỗ trợ / vướng mắc",
  "Issue Updated": "Vướng mắc đã được cập nhật",
  "Permit Workflow Updated": "Quy trình giấy phép đã được cập nhật",
  "Milestone Updated": "Mốc tiến độ đã được cập nhật",
  "User Created": "Đã tạo người dùng",
  "User Access Updated": "Quyền truy cập người dùng đã được cập nhật",
  "Agency Created": "Đã tạo cơ quan",
  "Agency Status Updated": "Trạng thái cơ quan đã được cập nhật",
  "Manage users, role assignments, and agency entities across the operating model.": "Quản lý người dùng, phân vai trò và đơn vị cơ quan trong toàn bộ mô hình vận hành.",
  "Add User": "Thêm người dùng",
  "Add Agency": "Thêm cơ quan",
  "Total Users": "Tổng số người dùng",
  "Active Users": "Người dùng hoạt động",
  "Agencies": "Cơ quan",
  "Inactive Accounts": "Tài khoản ngừng hoạt động",
  "Search users...": "Tìm kiếm người dùng...",
  "Search agencies...": "Tìm kiếm cơ quan...",
  "Last login": "Đăng nhập gần nhất",
  "active requests": "yêu cầu đang xử lý",
  "Edit User": "Chỉnh sửa người dùng",
  "Full Name": "Họ và tên",
  "Email": "Email",
  "Role": "Vai trò",
  "Organization": "Tổ chức",
  "Status": "Trạng thái",
  "Cancel": "Hủy",
  "Save User": "Lưu người dùng",
  "Edit Agency": "Chỉnh sửa cơ quan",
  "Agency Name": "Tên cơ quan",
  "Short Name": "Tên viết tắt",
  "Contact Person": "Người liên hệ",
  "Phone": "Số điện thoại",
  "Type": "Loại",
  "Jurisdiction": "Thẩm quyền",
  "Save Agency": "Lưu cơ quan",
  "Leadership view across pipeline conversion, portfolio execution, operational risk, and agency responsiveness.": "Góc nhìn lãnh đạo về chuyển đổi cơ hội, triển khai danh mục, rủi ro vận hành và mức độ phản hồi của cơ quan.",
  "Leadership Attention": "Điểm cần lãnh đạo lưu ý",
  "alerts": "cảnh báo",
  "Critical issue": "Vướng mắc nghiêm trọng",
  "No executive escalation items are currently open.": "Hiện không có mục leo thang điều hành nào đang mở.",
  "Investment Analytics": "Phân tích đầu tư",
  "Funnel": "Phễu",
  "By Sector": "Theo ngành",
  "Trend": "Xu hướng",
  "Portfolio Health": "Sức khỏe danh mục",
  "tracked projects": "dự án đang theo dõi",
  "Ready": "Sẵn sàng",
  "Low quality": "Chất lượng thấp",
  "Execution Metrics": "Chệ số triển khai",
  "Portfolio-wide": "Toàn danh mục",
  "Risk Queue": "Hàng đợi rủi ro",
  "Critical": "Nghiêm trọng",
  "Leadership summary": "Tóm tắt điều hành",
  "The platform is strongest where project quality, opportunity conversion, and execution responsiveness are visible together in one operating view.": "Nền tảng phát huy hiệu quả nhất khi chất lượng dự án, chuyển đổi cơ hội và mức độ phản hồi triển khai được nhìn thấy cùng nhau trong một góc nhìn vận hành.",
  "Agency work queue for investor services, SLA risk handling, and request resolution notes.": "Hàng đợi công việc của cơ quan cho dịch vụ nhà đầu tư, xử lý rủi ro SLA và ghi chú giải quyết yêu cầu.",
  "Escalation Queue": "Hàng đợi leo thang",
  "action items": "mục cần xử lý",
  "No service requests currently need escalation.": "Hiện không có yêu cầu dịch vụ nào cần leo thang.",
  "Search service, applicant, or project": "Tìm theo dịch vụ, đơn vị nộp hoặc dự án",
  "All statuses": "Tất cả trạng thái",
  "Request Processing Queue": "Hàng đợi xử lý yêu cầu",
  "visible": "hiển thị",
  "Assigned": "Phân công",
  "Process request": "Xử lý yêu cầu",
  "Workflow status": "Trạng thái quy trình",
  "Processing note": "Ghi chú xử lý",
  "Add next-step notes, requested documents, or approval context": "Thêm ghi chú bước tiếp theo, tài liệu yêu cầu hoặc bối cảnh phê duyệt",
  "Save workflow update": "Lưu cập nhật quy trình",
  "No service requests match the current filters.": "Không có yêu cầu dịch vụ nào khớp với bộ lọc hiện tại.",
  "Assigned permit workload with deadline urgency and fast status updates.": "Khối lượng công việc giấy phép được phân công với mức độ khẩn theo hạn và cập nhật trạng thái nhanh.",
  "Search by project or permit type...": "Tìm theo dự án hoặc loại giấy phép...",
  "priority": "ưu tiên",
  "Deadline": "Hạn chót",
  "Update": "Cập nhật",
  "Comments / Notes": "Nhận xét / Ghi chú",
  "Add processing notes...": "Thêm ghi chú xử lý...",
  "Save Update": "Lưu cập nhật",
  "Prioritize, assign, and resolve execution issues with visible severity and ownership.": "Ưu tiên, phân công và giải quyết các vướng mắc triển khai với mức độ nghiêm trọng và đầu mối rõ ràng.",
  "Search issues...": "Tìm kiếm vướng mắc...",
  "All Priorities": "Tất cả mức ưu tiên",
  "High": "Cao",
  "Medium": "Trung bình",
  "Low": "Thấp",
  "Open": "Mở",
  "Resolved": "Đã giải quyết",
  "Closed": "Đã đóng",
  "Reported": "Báo cáo",
  "Updated": "Cập nhật",
  "New Intake":"Quan tâm",
  "Initial Review":"Trao đổi sơ bộ",
  "Due Diligence":"Trao đổi chuyên sâu",
  "Negotiation":"Đàm phán chính thức",
  "Published":"Đã công bố",
  "Resolution Notes": "Ghi chú xử lý",
  "Describe actions taken...": "Mô tả hành động đã thực hiện...",
  "Requires Attention":"Thông tin nổi bật",
  "Save": "Lưu",
  "All":"Tất cả",
  "Registration":"Đăng ký",
  "Construction":"Xây dựng",
  "Trade":"Thương mại",
  "Safety":"An toàn",
  "Labor":"Lao động",
  "Department of Planning & Investment":"Sở Kế hoạch và Đầu tư",
  "working days":"ngày làm việc",
  "Business Registration Office":"Phòng Đăng ký Kinh doanh",
  "Dept. of Natural Resources & Environment":"Sở Tài nguyên và Môi trường",
  "Dept. of Construction":"Sở Xây dựng",
  "of construction value":"giá trị xây dựng",
  "Land Use Rights Certificate (LURC)":"Giấy chứng nhận quyền sử dụng đất",
  "Red Book":"Sổ đỏ",
  "certification confirming land use rights allocation for the project site.":"Chứng nhận xác nhận quyền sử dụng đất được cấp cho khu đất dự án.",
  "General Dept. of Customs":"Tổng cục Hải quan",
  "Police - Fire Department":"Cảnh sát PCCC",
  "VND 300,000":"300.000 VNĐ",
  "Dept. of Labor, Invalids & Social Affairs":"Sở Lao động - Thương binh và Xã hội",
  "Action-first monitoring for new leads, aging opportunities, and coordination handoffs.": "Theo dõi nhà đầu tư dự án",
  "items": "mục",
  "No overdue or unassigned opportunities require immediate action.": "Không có cơ hội quá hạn hoặc chưa phân công nào cần xử lý ngay.",
  "Active Opportunities": "Số dự án được tương tác",
  "This Month New": "Mới trong tháng",
  "Conversion Rate": "Tỷ lệ chuyển đổi",
  "Avg Days to Close": "Thời gian phê duyệt trung bình",
  "Search investor or project...": "Tìm nhà đầu tư hoặc dự án...",
  "All Stages": "Tất cả giai đoạn",
  "List": "Danh sách",
  "Kanban": "Kanban",
  "View": "Xem",
  "Total pipeline value": "Tổng giá trị đường ống",
  "No active execution workspaces yet": "Chưa có không gian thực thi đang hoạt động",
  "Once your opportunity is approved or moved into the final coordination phase, this workspace will show progress, risks, and support actions.": "Khi cơ hội đầu tư được phê duyệt hoặc chuyển sang giai đoạn điều phối cuối, không gian này sẽ hiển thị tiến độ, rủi ro và các hành động hỗ trợ.",
  "Explore projects": "Khám phá dự án",
  "Investor-facing delivery cockpit for project progress, support requests, and execution risk visibility.": "Bảng điều hành dành cho nhà đầu tư để theo dõi tiến độ dự án, yêu cầu hỗ trợ và rủi ro trong quá trình triển khai.",
  "Portfolio Selection": "Chọn danh mục",
  "active items": "hạng mục đang hoạt động",
  "Average Progress": "Tiến độ trung bình",
  "Open Issues": "Vấn đề đang mở",
  "Investment": "Khoản đầu tư",
  "Execution Milestones": "Mốc thực thi",
  "tracked": "được theo dõi",
  "days overdue": "ngày quá hạn",
  "days left": "ngày còn lại",
  "Coordination History": "Lịch sử phối hợp",
  "updates": "cáº­p nháº­t",
  "Support Request": "Yêu cầu hỗ trợ",
  "Direct to operations": "Gửi trực tiếp tới vận hành",
  "Support request submitted": "Đã gửi yêu cầu hỗ trợ",
  "The operations team will respond within 24 hours.": "Đội vận hành sẽ phản hồi trong vòng 24 giờ.",
  "Submit another request": "Gửi yêu cầu khác",
  "Describe the support need, permit blocker, documentation issue, or coordination request": "Mô tả nhu cầu hỗ trợ, vướng mắc giấy phép, vấn đề hồ sơ hoặc yêu cầu phối hợp",
  "Submit support request": "Gửi yêu cầu hỗ trợ",
  "Current Risks": "Rủi ro hiện tại",
  "No open execution risks are currently logged for this project.": "Hiện chưa có rủi ro thực thi đang mở nào được ghi nhận cho dự án này.",
  "Quick Actions": "Thao tác nhanh",
  "Investor tools": "Công cụ nhà đầu tư",
  "Open project dossier": "Mở hồ sơ dự án",
  "Browse B2G services": "Xem dịch vụ B2G",
  "Review service requests": "Xem yêu cầu dịch vụ",
  "B2G Service Catalog": "Danh mục dịch vụ B2G",
  "Browse licensing, registration, and compliance services needed to move investor projects through execution.": "Xem các dịch vụ cấp phép, đăng ký và tuân thủ cần thiết để đưa dự án đầu tư vào giai đoạn triển khai.",
  "Service Categories": "Nhóm dịch vụ",
  "available": "khả dụng",
  "Available Services": "Dịch vụ hiện có",
  "Investor workflow": "Quy trình nhà đầu tư",
  "required documents": "tài liệu bắt buộc",
  "Processing Time": "Thời gian xử lý",
  "Fee": "Phí",
  "Service Description": "Mô tả dịch vụ",
  "Required Documents": "Tài liệu bắt buộc",
  "Apply for service": "Nộp hồ sơ dịch vụ",
  "Service Application": "Hồ sơ dịch vụ",
  "Attach the project and supporting documents before routing the request to the responsible agency.": "Gắn dự án và hồ sơ hỗ trợ trước khi chuyển yêu cầu tới cơ quan phụ trách.",
  "Associated Project": "Dự án liên quan",
  "Select project": "Chọn dự án",
  "Document Upload": "Tải tài liệu lên",
  "Upload required files or simulate the intake package.": "Tải lên tệp bắt buộc hoặc mô phỏng bộ hồ sơ tiếp nhận.",
  "Simulate upload": "Mô phỏng tải lên",
  "Additional Notes": "Ghi chú bổ sung",
  "Add context for the processing agency, missing items, or delivery constraints": "Bổ sung bối cảnh cho cơ quan xử lý, các mục còn thiếu hoặc ràng buộc triển khai",
  "Uploaded Files": "Tệp đã tải lên",
  "Back": "Quay lại",
  "Submit application": "Gửi hồ sơ",
  "Application Submitted": "Đã gửi hồ sơ",
  "The request has been routed into the service workflow and can now be tracked from your request list.": "Yêu cầu đã được chuyển vào quy trình dịch vụ và hiện có thể theo dõi từ danh sách yêu cầu của bạn.",
  "Expected processing time": "Thời gian xử lý dự kiến",
  "Done": "Hoàn tất",
  "Standardize project onboarding, monitor publish readiness, and enforce minimum dataset quality.": "Chuẩn hóa khởi tạo dự án, theo dõi mức độ sẵn sàng công bố và bảo đảm chất lượng dữ liệu tối thiểu.",
  "Create Project": "Tạo dự án",
  "low-quality projects": "dự án chất lượng dữ liệu thấp",
  "Total Projects": "Tổng số dự án",
  "Project List": "Danh sách dự án",
  "Data Quality Dashboard": "Bảng điều khiển chất lượng dữ liệu",
  "Search projects...": "Tìm kiếm dự án...",
  "Not published": "Chưa công bố",
  "Data Governance": "Quản trị dữ liệu",
  "Projects must achieve at least 80% completeness and have accountable ownership before publishing.": "Dự án phải đạt tối thiểu 80% độ đầy đủ dữ liệu và có đơn vị chịu trách nhiệm rõ ràng trước khi công bố.",
  "Below threshold": "Dưới ngưỡng",
  "Project Name *": "Tên dự án *",
  "Official project name": "Tên dự án chính thức",
  "Sector *": "Lĩnh vực *",
  "Infrastructure, Energy...": "Hạ tầng, nống lượng...",
  "Province *": "Tỉnh/Thành phố *",
  "Location *": "Địa điểm *",
  "Specific area / district": "Khu vực / quận cụ thể",
  "Total Budget (USD M)": "Tổng ngân sách (triệu USD)",
  "Min Investment (USD M)": "Vốn đầu tư tối thiểu (triệu USD)",
  "Project description...": "Mô tả dự án...",
  "Save as Draft": "Lưu bản nháp",
  "TBD": "Sắp cập nhật",
  "New draft project pending full setup.": "Dự án bản nháp mới đang chờ hoàn thiện khởi tạo.",
  "Integrated renewable energy and storage park in Can Gio, designed to strengthen Ho Chi Minh City\\'s clean-energy supply chain with resilient grid integration and urban decarbonization infrastructure.": "Công viên năng lượng tái tạo và lưu trữ tích hợp tại Cần Giờ, được thiết kế nhằm củng cố chuỗi cung ứng năng lượng sạch của TP. Hồ Chí Minh với khả năng tích hợp lưới điện bền vững và hạ tầng giảm phát thải đô thị.",
  "Strategic advanced manufacturing and logistics zone in Cu Chi, designed for high-tech industry, urban supply chains, and export-oriented production with fully integrated infrastructure support.": "Khu sản xuất tiên tiến và logistics chiến lược tại Củ Chi, được thiết kế cho công nghiệp công nghệ cao, chuỗi cung ứng đô thị và sản xuất định hướng xuất khẩu với hạ tầng hỗ trợ tích hợp đầy đủ.",
  "Premium integrated tourism, hospitality, and convention development along the Saigon River, combining 5-star accommodation, business events, and entertainment in a flagship Ho Chi Minh City destination.": "Dự án du lịch, lưu trú và hội nghị tích hợp cao cấp dọc sông Sài Gòn, kết hợp lưu trú 5 sao, sự kiện doanh nghiệp và giải trí tại một điểm đến biểu tượng của TP. Hồ Chí Minh.",
  "Ho Chi Minh City\\'s flagship technology innovation cluster at Saigon Hi-Tech Park, designed to attract R&D centers, semiconductor manufacturing, and deep-tech startups with world-class facilities.": "Cụm đổi mới công nghệ chủ lực của TP. Hồ Chí Minh tại Khu Công nghệ cao Sài Gòn, được thiết kế để thu hút các trung tâm R&D, sản xuất bán dẫn và startup deep-tech với cơ sở vật chất đẳng cấp quốc tế.",
  "Integrated agricultural processing and cold-chain logistics complex in Cu Chi, supporting Ho Chi Minh City\\'s regional food distribution, export connectivity, and value-added agro-industry ecosystem.": "Tổ hợp chế biến nông nghiệp và logistics chuỗi lạnh tích hợp tại Củ Chi, hỗ trợ phân phối lương thực vùng, kết nối xuất khẩu và hệ sinh thái nông nghiệp giá trị gia tăng của TP. Hồ Chí Minh.",
  "Initial screening completed - qualified": "Sàng lọc ban đầu hoàn tất - đạt điều kiện",
  "Qualified - forwarded to tech committee": "Đạt điều kiện - đã chuyển tới hội đồng kỹ thuật",
  "Conflicting regulations between the local riverfront plan and aviation safety envelope. Seeking city-level planning guidance.": "Có xung đột giữa quy hoạch ven sông địa phương và hành lang an toàn hàng không. Đang xin hướng dẫn quy hoạch cấp thành phố.",
  "\\'Red Book\\' certification confirming land use rights allocation for the project site.": "Chứng nhận \"Sổ đỏ\" xác nhận quyền sử dụng đất được giao cho khu đất thực hiện dự án.",
  "Upload at least one supporting document.": "Tải lên ít nhất một tài liệu hỗ trợ.",
  "Define at least one milestone and delivery phase.": "Xác định ít nhất một mốc tiến độ và giai đoạn triển khai.",
  "Add an investor Q&A entry or readiness note.": "Thêm một mục hỏi đáp nhà đầu tư hoặc ghi chú mức độ sẵn sàng.",
  "Complete publish-readiness fields to reach the 80% threshold.": "Hoàn tất các trường sẵn sàng công bố để đạt ngưỡng 80%.",
  "Move the project from draft to review once the draft fields are validated.": "Chuyển dự án từ bản nháp sang chờ duyệt sau khi xác thực các trường nháp.",
  "Back to project": "Quay lại dự án",
  "Edit Project": "Chỉnh sửa dự án",
  "Update commercial details, readiness fields, and publication quality in one working draft.": "Cập nhật thông tin thương mại, trường sẵn sàng và chất lượng công bố trong cùng một bản làm việc.",
  "Save changes": "Lưu thay đổi",
  "Data Quality Fix Mode": "Chế độ sửa chất lượng dữ liệu",
  "issues": "vấn đề",
  "Project Name": "Tên dự án",
  "Budget (USD M)": "Ngân sách (triệu USD)",
  "Minimum Investment (USD M)": "Vốn đầu tư tối thiểu (triệu USD)",
  "Current Snapshot": "Tổng quan hiện tại",
  "Completeness": "Độ đầy đủ",
  "Missing Data Checklist": "Danh sách dữ liệu còn thiếu",
  "No missing-data blockers are currently detected.": "Hiện không phát hiện vướng mắc dữ liệu còn thiếu.",
  "Save Status": "Trạng thái lưu",
  "Saved": "Đã lưu",
  "Changes saved to shared app state": "Các thay đổi đã được lưu vào trạng thái dùng chung của ứng dụng",
  "The updated project now stays in sync across project management, project view, and investor-facing pages during this local session.": "Dự án đã cập nhật hiện đồng bộ giữa quản lý dự án, trang xem dự án và các trang dành cho nhà đầu tư trong phiên cục bộ này.",
  "Update the draft fields and save when you are ready to validate the changes.": "Cập nhật các trường bản nháp và lưu khi bạn sẵn sàng xác thực thay đổi.",
  "Operational dashboard for active projects, overdue signals, and cross-agency coordination.": "Bảng điều hành cho các dự án đang hoạt động, tín hiệu quá hạn và điều phối liên cơ quan.",
  "Overdue by": "Quá hạn",
  "days": "ngày",
  "No critical execution blockers at this time.": "Hiện chưa có trở ngại thực thi nghiêm trọng.",
  "Pending Permits": "Giấy phép chờ xử lý",
  "In Progress Milestones": "Mốc đang triển khai",
  "Project Health Overview": "Tổng quan sức khỏe dự án",
  "open issues": "vấn đề đang mở",
  "permit actions": "đầu việc giấy phép",
  "Milestone Tracker": "Theo dõi mốc tiến độ",
  "Execution summary": "Tóm tắt thực thi",
  "Track project delivery, permit workload, and critical blockers in one operational view.": "Theo dõi tiến độ triển khai dự án, khối lượng giấy phép và các trở ngại nghiêm trọng trong một màn hình vận hành.",
  "Opportunity not found": "Không tìm thấy cơ hội",
  "Back to pipeline": "Quay lại đường ống",
  "leading a proposed": "đang dẫn dắt cam kết dự kiến",
  "commitment into": "đầu tư vào",
  "Last Updated": "Cập nhật lần cuối",
  "Activities": "Hoạt động",
  "Advance stage": "Chuyển giai đoạn",
  "Approve opportunity": "Phê duyệt cơ hội",
  "Approved and routed to execution": "Đã phê duyệt và chuyển sang thực thi",
  "The operator flow keeps approval intent, investor profile, and execution handoff in one place so the team does not lose context between stages.": "Quy trình vận hành giữ mục tiêu phê duyệt, hồ sơ nhà đầu tư và bàn giao thực thi trong cùng một nơi để đội ngũ không mất ngữ cảnh giữa các giai đoạn.",
  "Decision Pipeline": "Đường ống quyết định",
  "Unknown stage": "Giai đoạn không xác định",
  "Stage": "Giai đoạn",
  "Completed": "Hoàn thành",
  "Current focus": "Trọng tâm hiện tại",
  "Investor Intake Profile": "Hồ sơ tiếp nhận nhà đầu tư",
  "Decision-ready": "Sẵn sàng ra quyết định",
  "Representative": "Người đại diện",
  "Country": "Quốc gia",
  "Investor Type": "Loại nhà đầu tư",
  "Investment Structure": "Cấu trúc đầu tư",
  "Fund Source": "Nguồn vốn",
  "Experience": "Kinh nghiệm",
  "Project Match": "Mức độ phù hợp với dự án",
  "Active review": "Đang xem xét",
  "Province not available": "Chưa có thông tin tỉnh/thành",
  "Open project": "Mở dự án",
  "Operator Note": "Ghi chú vận hành",
  "Activity log update": "Cập nhật nhật ký hoạt động",
  "Record meeting outcomes, due diligence findings, or escalation notes": "Ghi nhận kết quả họp, phát hiện thẩm định hoặc ghi chú leo thang",
  "Add activity note": "Thêm ghi chú hoạt động",
  "Decision Support": "Hỗ trợ ra quyết định",
  "Pending sign-off": "Chờ phê chuẩn",
  "Validate investor capacity and fund source.": "Xác thực năng lực nhà đầu tư và nguồn vốn.",
  "Confirm project alignment with execution readiness.": "Xác nhận mức độ phù hợp của dự án với khả năng sẵn sàng triển khai.",
  "Capture all negotiation changes before approval.": "Ghi nhận toàn bộ thay đổi trong đàm phán trước khi phê duyệt.",
  "Activity Timeline": "Dòng thời gian hoạt động",
  "events": "sự kiện",
  "Approve this opportunity?": "Phê duyệt cơ hội này?",
  "Execution workspace will be created for": "Không gian thực thi sẽ được tạo cho",
  "Confirm approval": "Xác nhận phê duyệt",
  "Stage advanced to Initial Review.": "Đã chuyển giai đoạn sang Đánh giá ban đầu.",
  "Stage advanced to Due Diligence.": "Đã chuyển giai đoạn sang Thẩm định.",
  "Stage advanced to Negotiation.": "Đã chuyển giai đoạn sang Đàm phán.",
  "Stage advanced to Approved.": "Đã chuyển giai đoạn sang Được phê duyệt.",
  "Opportunity approved. Execution workspace created automatically.": "Cơ hội đã được phê duyệt. Không gian thực thi được tạo tự động.",
  "Each required data item must have a responsible user.": "Mỗi hạng mục dữ liệu bắt buộc phải có người dùng chịu trách nhiệm.",
  "Complete or close all required data assignments before publication review.": "Hoàn tất hoặc chốt toàn bộ phân công dữ liệu bắt buộc trước khi rà soát công bố.",
  "completed": "hoàn thành",
  "Required data item": "Hạng mục dữ liệu bắt buộc",
  "Responsible agency": "Cơ quan phụ trách",
  "Responsible user": "Người phụ trách",
  "Assignment status": "Trạng thái phân công",
  "missing": "thiếu",
  "assigned": "đã giao",
  "in progress": "đang thực hiện",
  "Remove": "Xóa",
  "Describe what must be submitted or validated for this item": "Mô tả nội dung cần nộp hoặc xác thực cho hạng mục này",
  "Agency": "Cơ quan",
  "Owner": "Người phụ trách",
  "No required data assignments have been defined for this project yet.": "Dự án này chưa được định nghĩa phân công dữ liệu bắt buộc.",
  "Add required data item": "Thêm hạng mục dữ liệu bắt buộc",
  "Example: traffic impact study, utility confirmation, legal boundary memo": "Ví dụ: báo cáo tác động giao thông, xác nhận hạ tầng kỹ thuật, biên bản pháp lý ranh giới",
  "Required data items": "Hạng mục dữ liệu bắt buộc",
  "Owned items": "Hạng mục đã có chủ",
  "Completed items": "Hạng mục hoàn thành",
  "No ownership matrix": "Chưa có ma trận phân công",
  "Required Data Assignment Created": "Đã tạo phân công dữ liệu bắt buộc",
  "Required Data Assignment Updated": "Đã cập nhật phân công dữ liệu bắt buộc",
  "Required Data Status": "Trạng thái dữ liệu bắt buộc",
  "No required data items have been published for this project yet.": "Chưa có hạng mục dữ liệu bắt buộc nào được công bố cho dự án này.",
  "Open Projects": "Dự án đang mở",
  "Total Value": "Tổng giá trị",
  "Sectors": "Lĩnh vực",
  "Average IRR": "IRR trung bình",
  "Traffic impact assessment": "Đánh giá tác động giao thông",
  "Land boundary legal review": "Rà soát pháp lý ranh giới đất",
  "Grid connection confirmation": "Xác nhận kết nối lưới điện",
  "Fire safety pre-clearance memo": "Biên bản tiền thẩm định an toàn PCCC",
  "Confirm traffic management interface": "Xác nhận phương án phối hợp điều tiết giao thông",
  "Validate final intersection phasing and construction detour routing before investor circulation.": "Xác thực phương án phân kỳ nút giao cuối cùng và tuyến điều hướng giao thông thi công trước khi gửi cho nhà đầu tư.",
  "Awaiting final agency confirmation of frontage traffic sequencing.": "Đang chờ cơ quan xác nhận cuối cùng về phân luồng giao thông mặt tiền.",
  "Issue land-boundary confirmation note": "Ban hành biên bản xác nhận ranh giới đất",
  "Issue the signed coordination note confirming surveyed land boundaries for the investor pack.": "Ban hành biên bản phối hợp đã ký xác nhận ranh giới đất khảo sát cho bộ hồ sơ nhà đầu tư.",
  "Completed and filed in the project room.": "Đã hoàn thành và lưu trong hồ sơ dự án.",
  "Finalize interconnection work package": "Hoàn tất gói công việc đấu nối",
  "Close the agency review on interconnection works, energization dependencies, and handover sequencing.": "Chốt rà soát của cơ quan về công tác đấu nối, các phụ thuộc cấp điện và trình tự bàn giao.",
  "Overdue mock case for project-processing alerts.": "Tình huống mô phỏng quá hạn cho cảnh báo xử lý dự án.",
  "Publish fire-safety readiness handoff": "Công bố biên bản bàn giao sẵn sàng PCCC",
  "Publish the readiness handoff confirming fire-safety preconditions are cleared for the next phase.": "Công bố biên bản bàn giao sẵn sàng xác nhận các điều kiện tiên quyết về PCCC đã được đáp ứng cho giai đoạn tiếp theo.",
  "Completed mock case for processing progress.": "Tình huống mô phỏng đã hoàn thành cho tiến độ xử lý.",
  "List of Issues reported": "Danh sách vướng mắc đã báo cáo",
  "Issue Title/Summary": "Tiêu đề/Tóm tắt vướng mắc",
  "Reported By": "Đơn vị báo cáo",
  "Reported Time": "Thời gian báo cáo",
  "PIC/Agency in charge": "PIC/Cơ quan phụ trách",
  "B2G Request": "Yêu cầu Dịch vụ công",
  "Request type": "Loại yêu cầu",
  "Request By": "Đơn vị gửi yêu cầu",
  "RequestTime": "Thời gian gửi yêu cầu",
  "No issues reported for this project yet.": "Chưa có vướng mắc nào được báo cáo cho dự án này.",
  "No B2G requests for this project yet.": "Chưa có yêu cầu Dịch vụ công nào cho dự án này.",
  "open": "mở",
  "resolved": "đã xử lý",
  "closed": "đã đóng",
  "info required": "cần bổ sung thông tin",
  "No active execution item matched the selected investor profile. Showing available demo execution items instead.": "Không có hạng mục triển khai phù hợp với hồ sơ nhà đầu tư đã chọn. Hệ thống đang hiển thị dữ liệu triển khai mẫu hiện có.",
  "Support requests created by the investor, grouped by project for quick follow-up.": "Danh sách yêu cầu hỗ trợ do nhà đầu tư tạo, được nhóm theo dự án để theo dõi nhanh.",
  "No support request yet": "Chưa có yêu cầu hỗ trợ",
  "Create a support request from the execution workspace and it will appear here.": "Tạo yêu cầu hỗ trợ từ Không gian triển khai và yêu cầu sẽ xuất hiện tại đây.",
  "Open execution workspace": "Mở không gian triển khai",
  "Review support requests": "Xem yêu cầu hỗ trợ",
  "0-24h": "0-24 giờ",
  "24-48h": "24-48 giờ",
  ">48h": "Trên 48 giờ",
  "Back to explorer": "Quay lại trang khám phá",
  "Current step": "Bước hiện tại",
  "Deal breakers": "Yếu tố loại trừ",
  "Draft saved": "Đã lưu bản nháp",
  "Escalation to leadership queue": "Leo thang lên hàng đợi lãnh đạo",
  "Fast upload / import": "Tải nhanh / nhập nhanh",
  "Immediate owner review": "Chủ phụ trách xem xét ngay",
  "Intake value": "Giá trị của tiếp nhận",
  "Investor Intake Form": "Biểu mẫu tiếp nhận nhà đầu tư",
  "Meeting Ticket": "Phiếu cuộc họp",
  "Next steps": "Các bước tiếp theo",
  "Normal response window": "Khung phản hồi thông thường",
  "Opportunity": "Cơ hội",
  "Progressive intake that captures investor intent quickly, expands only when needed, and immediately creates the right workflow objects after submission.": "Quy trình tiếp nhận từng bước giúp nắm bắt nhanh ý định của nhà đầu tư, chỉ mở rộng khi cần và tạo ngay các đối tượng quy trình phù hợp sau khi nộp.",
  "Q&A Thread": "Luồng Hỏi đáp",
  "Reminder to operator and assigned owner": "Nhắc việc tới cán bộ vận hành và người phụ trách đã được giao",
  "Save draft": "Lưu bản nháp",
  "Submit intake": "Gửi hồ sơ tiếp nhận",
  "The intake was converted into tracked government workflow objects so the team can respond without asking you to repeat information.": "Hồ sơ tiếp nhận đã được chuyển thành các đối tượng quy trình theo dõi của cơ quan nhà nước để đội ngũ có thể phản hồi mà không cần yêu cầu bạn lặp lại thông tin.",
  "Timeline": "Tiến độ thời gian",
  "Upcoming step": "Bước sắp tới",
  "View my opportunities": "Xem các cơ hội của tôi",
  "Website": "Trang web",
  "Why it matters": "Vì sao điều này quan trọng",
  "Your interest has been submitted": "Mối quan tâm của bạn đã được gửi",
  "Quick intent": "Ý định nhanh",
  "Expanded intake": "Hồ sơ mở rộng",
  "Interest Type": "Loại quan tâm",
  "Create an initial opportunity without extra coordination.": "Tạo một cơ hội ban đầu mà chưa cần điều phối bổ sung.",
  "Meeting requests are treated as high priority.": "Yêu cầu họp được xử lý ở mức ưu tiên cao.",
  "Use this when the investor primarily needs more information.": "Dùng lựa chọn này khi nhà đầu tư chủ yếu cần thêm thông tin.",
  "Example: 50,000,000 or 50M": "Ví dụ: 50.000.000 hoặc 50M",
  "Progressive form": "Biểu mẫu từng bước",
  "You only need these fields to unlock the expanded intake. Everything else can be filled in the next step or saved as a draft.": "Chỉ cần các trường này để mở phần hồ sơ mở rộng. Những nội dung còn lại có thể điền ở bước tiếp theo hoặc lưu thành bản nháp.",
  "Auto-priority rule": "Quy tắc ưu tiên tự động",
  "Meeting requests and investor questions are automatically handled as high priority.": "Yêu cầu họp và câu hỏi của nhà đầu tư sẽ tự động được xử lý ở mức ưu tiên cao.",
  "Normal requests remain on the standard 0-24h intake response window unless urgency is raised.": "Các yêu cầu thông thường vẫn theo khung phản hồi tiếp nhận 0-24 giờ, trừ khi mức độ khẩn được nâng lên.",
  "Company info": "Thông tin doanh nghiệp",
  "Will be added in the expanded step.": "Sẽ được bổ sung ở bước hồ sơ mở rộng.",
  "Draft support": "Hỗ trợ bản nháp",
  "Drafts are saved locally so the investor can return later.": "Bản nháp được lưu cục bộ để nhà đầu tư có thể quay lại sau.",
  "Current priority": "Mức ưu tiên hiện tại",
  "Section 1 - Company Info": "Phần 1 - Thông tin doanh nghiệp",
  "Auto-fill, upload a company profile, or paste a profile link.": "Tự động điền, tải hồ sơ doanh nghiệp lên hoặc dán liên kết hồ sơ.",
  "Company name": "Tên doanh nghiệp",
  "Company type": "Loại hình doanh nghiệp",
  "Select company type": "Chọn loại hình doanh nghiệp",
  "Company profile link": "Liên kết hồ sơ doanh nghiệp",
  "Company profile upload": "Tải hồ sơ doanh nghiệp",
  "Company profile": "Hồ sơ doanh nghiệp",
  "Upload PDF": "Tải PDF",
  "Section 2 - Interest Type": "Phần 2 - Loại quan tâm",
  "Choose the primary investor action that should be triggered by this intake.": "Chọn hành động chính của nhà đầu tư sẽ được kích hoạt từ đợt tiếp nhận này.",
  "Register strategic interest and create an opportunity.": "Ghi nhận sự quan tâm chiến lược và tạo cơ hội đầu tư.",
  "Create both the opportunity and a meeting workflow ticket.": "Tạo đồng thời cơ hội đầu tư và phiếu quy trình cho cuộc họp.",
  "Create the opportunity and let the investor ask for more information.": "Tạo cơ hội đầu tư và cho phép nhà đầu tư yêu cầu thêm thông tin.",
  "Section 3 - Investment Intent": "Phần 3 - Ý định đầu tư",
  "This is the most important section because it defines investment appetite and expected deal structure.": "Đây là phần quan trọng nhất vì xác định khẩu vị đầu tư và cấu trúc giao dịch kỳ vọng.",
  "Intended investment size": "Quy mô đầu tư dự kiến",
  "Investment type": "Loại hình đầu tư",
  "Select investment type": "Chọn loại hình đầu tư",
  "Ownership expectation (%)": "Kỳ vọng sở hữu (%)",
  "Example: 49%": "Ví dụ: 49%",
  "Timeline to invest": "Thời gian dự kiến đầu tư",
  "Example: 6-9 months after approval": "Ví dụ: 6-9 tháng sau khi được chấp thuận",
  "Section 4 - Interest Hint": "Phần 4 - Gợi ý mối quan tâm",
  "Investor interest reasons are valuable because they enrich appetite, sectors, and ticket-size signals for later classification.": "Các lý do quan tâm của nhà đầu tư rất có giá trị vì giúp làm giàu dữ liệu về khẩu vị, lĩnh vực và quy mô vé đầu tư cho bước phân loại sau này.",
  "Specific interest note": "Ghi chú quan tâm cụ thể",
  "Add strategic context, market rationale, technology angle, or supply-chain logic.": "Bổ sung bối cảnh chiến lược, cơ sở thị trường, góc độ công nghệ hoặc logic chuỗi cung ứng.",
  "Section 5 - Requirements & Conditions": "Phần 5 - Yêu cầu và điều kiện",
  "Capture must-have conditions, deal breakers, and any specific requirements before follow-up begins.": "Ghi nhận các điều kiện bắt buộc, các yếu tố loại trừ và những yêu cầu cụ thể trước khi bắt đầu theo dõi tiếp.",
  "Must-have": "Điều kiện bắt buộc",
  "Specific requirements": "Yêu cầu cụ thể",
  "Add deal conditions, dependencies, legal requirements, or execution prerequisites.": "Bổ sung điều kiện giao dịch, các phụ thuộc, yêu cầu pháp lý hoặc điều kiện tiên quyết để triển khai.",
  "Section 6 - Questions": "Phần 6 - Câu hỏi",
  "If the investor asks a question, the post-processing flow will create a Q&A thread automatically.": "Nếu nhà đầu tư đặt câu hỏi, luồng xử lý sau tiếp nhận sẽ tự động tạo một luồng Hỏi đáp.",
  "Investor question": "Câu hỏi của nhà đầu tư",
  "Enter a free-text investor question for due diligence or clarification.": "Nhập câu hỏi dạng tự do của nhà đầu tư để phục vụ thẩm định hoặc làm rõ thông tin.",
  "Section 7 - Meeting Request": "Phần 7 - Yêu cầu cuộc họp",
  "Meeting details become mandatory only when the investor selects Request Meeting.": "Thông tin cuộc họp chỉ bắt buộc khi nhà đầu tư chọn Yêu cầu cuộc họp.",
  "Required": "Bắt buộc",
  "Optional": "Tùy chọn",
  "Preferred date": "Ngày mong muốn",
  "Preferred time": "Giờ mong muốn",
  "Meeting type": "Hình thức họp",
  "Select meeting type": "Chọn hình thức họp",
  "Participants": "Thành phần tham dự",
  "Example: CIO, project counsel, technical advisor": "Ví dụ: CIO, cố vấn pháp lý dự án, cố vấn kỹ thuật",
  "Agenda": "Nội dung làm việc",
  "Outline the meeting agenda and the decisions needed from the session.": "Tóm tắt nội dung cuộc họp và các quyết định cần đạt được từ buổi làm việc.",
  "Select Request Meeting above if the investor wants the system to create a meeting coordination ticket.": "Hãy chọn Yêu cầu cuộc họp ở trên nếu nhà đầu tư muốn hệ thống tạo phiếu điều phối cuộc họp.",
  "Section 8 - Priority / Urgency": "Phần 8 - Mức độ ưu tiên / khẩn cấp",
  "Meeting requests and investor questions are automatically elevated to high priority, but urgent requests can still be raised manually.": "Yêu cầu họp và câu hỏi của nhà đầu tư sẽ tự động được nâng lên mức ưu tiên cao, nhưng các yêu cầu khẩn vẫn có thể được nâng thủ công.",
  "Effective priority": "Mức ưu tiên hiệu lực",
  "Selected priority": "Mức ưu tiên đã chọn",
  "This is the priority the post-processing workflow and SLA monitoring will use.": "Đây là mức ưu tiên mà luồng xử lý sau tiếp nhận và cơ chế giám sát SLA sẽ sử dụng.",
  "The selected normal priority is automatically raised because meeting requests and investor questions are treated as high priority in the workflow.": "Mức ưu tiên thông thường đã chọn được tự động nâng lên vì yêu cầu họp và câu hỏi của nhà đầu tư được xử lý ở mức ưu tiên cao trong quy trình.",
  "Review & submit": "Rà soát và gửi",
  "Check what will be created, enriched, and notified before the intake is submitted.": "Kiểm tra những gì sẽ được tạo, làm giàu dữ liệu và gửi thông báo trước khi hồ sơ được nộp.",
  "Company snapshot": "Tóm tắt doanh nghiệp",
  "Investment snapshot": "Tóm tắt đầu tư",
  "Requirements & conditions": "Yêu cầu và điều kiện",
  "Question & meeting": "Câu hỏi và cuộc họp",
  "Meeting request": "Yêu cầu cuộc họp",
  "Yes": "Có",
  "No": "Không",
  "Post-processing": "Xử lý sau tiếp nhận",
  "The system creates workflow objects, enriches the investor profile, and notifies the right teams immediately.": "Hệ thống sẽ tạo các đối tượng quy trình, làm giàu hồ sơ nhà đầu tư và thông báo ngay cho đúng đội ngũ liên quan.",
  "Create Opportunity": "Tạo cơ hội đầu tư",
  "The intake becomes a tracked opportunity in the government pipeline.": "Hồ sơ tiếp nhận sẽ trở thành một cơ hội được theo dõi trong đường ống xử lý của cơ quan nhà nước.",
  "Create Q&A Thread": "Tạo luồng Hỏi đáp",
  "A question entry is routed for response if the investor includes one.": "Nếu nhà đầu tư có câu hỏi, một mục Hỏi đáp sẽ được chuyển đi để phản hồi.",
  "Create Meeting Ticket": "Tạo phiếu cuộc họp",
  "A meeting workflow ticket is created when the investor requests a meeting.": "Một phiếu quy trình cuộc họp sẽ được tạo khi nhà đầu tư yêu cầu làm việc.",
  "Active": "Đang kích hoạt",
  "Not triggered": "Chưa kích hoạt",
  "Data enrichment": "Làm giàu dữ liệu",
  "Appetite": "Khẩu vị đầu tư",
  "To be extracted": "Sẽ được trích xuất",
  "Ticket size": "Quy mô vé đầu tư",
  "To data owners": "Gửi tới đơn vị phụ trách dữ liệu",
  "To government": "Gửi tới khối chính phủ",
  "To agency": "Gửi tới cơ quan xử lý",
  "Monitor new intake for follow-up if required": "Theo dõi hồ sơ tiếp nhận mới để xử lý tiếp nếu cần",
  "SLA & Escalation": "SLA và leo thang",
  "High-priority triggers": "Điều kiện kích hoạt ưu tiên cao",
  "Meeting requests and investor questions are always treated as high priority and can escalate after 48 hours without action.": "Yêu cầu họp và câu hỏi của nhà đầu tư luôn được xử lý ở mức ưu tiên cao và có thể bị leo thang nếu sau 48 giờ vẫn chưa có hành động.",
  "For the Government": "Đối với khối chính phủ",
  "No need to ask again. Deal classification starts immediately from the submitted intent and conditions.": "Không cần phải hỏi lại. Việc phân loại cơ hội có thể bắt đầu ngay từ ý định và điều kiện đã được nộp.",
  "For the Investor": "Đối với nhà đầu tư",
  "The intake feels fast, avoids a black-box experience, and gives a clear next-step path.": "Quy trình tiếp nhận tạo cảm giác nhanh, tránh trải nghiệm mơ hồ và cho thấy rõ các bước tiếp theo.",
  "For the System": "Đối với hệ thống",
  "Structured intake improves data quality, investor profiling, and conversion readiness.": "Tiếp nhận có cấu trúc giúp nâng cao chất lượng dữ liệu, hồ sơ hóa nhà đầu tư và mức độ sẵn sàng chuyển đổi.",
  "Auto workflow": "Luồng tự động",
  "Select an interest type and intended investment size before continuing.": "Hãy chọn loại quan tâm và quy mô đầu tư dự kiến trước khi tiếp tục.",
  "Complete the required company, intent, and meeting fields before moving to review.": "Hãy hoàn thành các trường bắt buộc về doanh nghiệp, ý định và cuộc họp trước khi chuyển sang bước rà soát.",
  "Complete the required company, intent, and meeting fields before submission.": "Hãy hoàn thành các trường bắt buộc về doanh nghiệp, ý định và cuộc họp trước khi gửi hồ sơ.",
  "Next step": "Bước tiếp theo",
  "Previous": "Quay lại",
  "Step 1 only asks for the core signal so the investor can start quickly and expand later.": "Bước 1 chỉ hỏi tín hiệu cốt lõi để nhà đầu tư có thể bắt đầu nhanh và mở rộng thông tin sau.",
  "Capture company profile, investment intent, conditions, questions, and meeting details in one structured submission.": "Thu thập hồ sơ doanh nghiệp, ý định đầu tư, điều kiện, câu hỏi và chi tiết cuộc họp trong một lần nộp có cấu trúc.",
  "Auto-fill can reuse previous company data so the investor does not need to start from scratch.": "Tự động điền có thể tái sử dụng dữ liệu doanh nghiệp trước đó để nhà đầu tư không phải bắt đầu lại từ đầu.",
  "Urgent": "Khẩn cấp"
};

export function translateText(value: string, language: Language) {
  if (language === 'en') return value;
  const cleanTranslated = cleanTextMap[value];
  return cleanTranslated ?? value;
}

export function getLocalizedNotifications(language: Language) {
  const base = [
    { id: '1', title: 'New Opportunity', message: 'Nguyen Corp submitted an intake for Smart City project', time: '5m ago', read: false, type: 'info' as const },
    { id: '2', title: 'Permit Approved', message: 'Construction permit for Da Nang Resort has been approved', time: '1h ago', read: false, type: 'success' as const },
    { id: '3', title: 'SLA Warning', message: 'Service request SR-2024-018 is approaching deadline', time: '2h ago', read: false, type: 'warning' as const },
    { id: '4', title: 'Milestone Completed', message: 'Phase 1 of Renewable Energy Park is complete', time: '1d ago', read: true, type: 'success' as const },
  ];

  return base.map((item) => ({
    ...item,
    title: translateText(item.title, language),
    message: translateText(item.message, language),
  }));
}

const NON_TRANSLATABLE_KEYS = new Set([
  'id',
  'projectId',
  'serviceId',
  'agencyId',
  'userId',
  'category',
  'status',
  'stage',
  'role',
  'organization',
  'priority',
  'slaStatus',
  'type',
  'icon',
  'image',
  'color',
  'fileUrl',
  'shortName',
  'permissions',
]);

function shouldSkipTranslation(key: string, value: string) {
  if (!value) return true;
  if (NON_TRANSLATABLE_KEYS.has(key)) return true;
  if (key.endsWith('Id')) return true;
  if (key.endsWith('At') || key.endsWith('Date') || key.toLowerCase().includes('deadline')) return true;
  if (/^https?:\/\//i.test(value)) return true;
  if (/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) return true;
  if (/^\+?[0-9()\-\s]{7,}$/.test(value)) return true;
  if (/^\d{4}-\d{2}-\d{2}(?:[ T]\d{2}:\d{2}(?::\d{2})?)?$/.test(value)) return true;
  return false;
}

function localizeDeep<T>(value: T, language: Language, key = ''): T {
  if (typeof value === 'string') {
    if (shouldSkipTranslation(key, value)) return value;
    return translateText(value, language) as T;
  }

  if (Array.isArray(value)) {
    if (NON_TRANSLATABLE_KEYS.has(key)) return value;
    return value.map((item) => localizeDeep(item, language, key)) as T;
  }

  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([entryKey, entryValue]) => [
        entryKey,
        localizeDeep(entryValue, language, entryKey),
      ]),
    ) as T;
  }

  return value;
}

export function getLocalizedData(language: Language) {
  if (language === 'en') {
    return {
      projects,
      opportunities,
      permits,
      issues,
      milestones,
      services,
      serviceRequests,
      users,
      agencies,
      executiveKPIs,
      funnelData,
      sectorInvestmentData,
      monthlyIntakeData,
    };
  }

  return {
    projects: localizeDeep(projects, language),
    opportunities: localizeDeep(opportunities, language),
    permits: localizeDeep(permits, language),
    issues: localizeDeep(issues, language),
    milestones: localizeDeep(milestones, language),
    services: localizeDeep(services, language),
    serviceRequests: localizeDeep(serviceRequests, language),
    users: localizeDeep(users, language),
    agencies: localizeDeep(agencies, language),
    executiveKPIs: localizeDeep(executiveKPIs, language),
    funnelData: localizeDeep(funnelData, language),
    sectorInvestmentData: localizeDeep(sectorInvestmentData, language),
    monthlyIntakeData: localizeDeep(monthlyIntakeData, language),
  };
}

const baseData = {
  projects: JSON.parse(JSON.stringify(projects)),
  opportunities: JSON.parse(JSON.stringify(opportunities)),
  permits: JSON.parse(JSON.stringify(permits)),
  issues: JSON.parse(JSON.stringify(issues)),
  milestones: JSON.parse(JSON.stringify(milestones)),
  services: JSON.parse(JSON.stringify(services)),
  serviceRequests: JSON.parse(JSON.stringify(serviceRequests)),
  users: JSON.parse(JSON.stringify(users)),
  agencies: JSON.parse(JSON.stringify(agencies)),
  executiveKPIs: JSON.parse(JSON.stringify(executiveKPIs)),
  funnelData: JSON.parse(JSON.stringify(funnelData)),
  sectorInvestmentData: JSON.parse(JSON.stringify(sectorInvestmentData)),
  monthlyIntakeData: JSON.parse(JSON.stringify(monthlyIntakeData)),
};

function replaceArray(target: any[], next: any[]) {
  target.splice(0, target.length, ...next);
}

function replaceObject(target: Record<string, any>, next: Record<string, any>) {
  Object.keys(target).forEach((key) => delete target[key]);
  Object.assign(target, next);
}

export function applyLocalizedMockData(language: Language) {
  const localized = language === 'en'
    ? baseData
    : getLocalizedData(language);

  replaceArray(projects as any[], JSON.parse(JSON.stringify(localized.projects)));
  replaceArray(opportunities as any[], JSON.parse(JSON.stringify(localized.opportunities)));
  replaceArray(permits as any[], JSON.parse(JSON.stringify(localized.permits)));
  replaceArray(issues as any[], JSON.parse(JSON.stringify(localized.issues)));
  replaceArray(milestones as any[], JSON.parse(JSON.stringify(localized.milestones)));
  replaceArray(services as any[], JSON.parse(JSON.stringify(localized.services)));
  replaceArray(serviceRequests as any[], JSON.parse(JSON.stringify(localized.serviceRequests)));
  replaceArray(users as any[], JSON.parse(JSON.stringify(localized.users)));
  replaceArray(agencies as any[], JSON.parse(JSON.stringify(localized.agencies)));
  replaceArray(funnelData as any[], JSON.parse(JSON.stringify(localized.funnelData)));
  replaceArray(sectorInvestmentData as any[], JSON.parse(JSON.stringify(localized.sectorInvestmentData)));
  replaceArray(monthlyIntakeData as any[], JSON.parse(JSON.stringify(localized.monthlyIntakeData)));
  replaceObject(executiveKPIs as Record<string, any>, JSON.parse(JSON.stringify(localized.executiveKPIs)));
}
